
ajax_fitting_room_product_list:
    pattern:  /ajax/fitting_room_product/{gender}/list/{page_number}/{limit}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:fittingRoomProductsList, page_number: 0, limit: 0}
  
ajax_fitting_feedback_json:
    pattern:  /ajax/fitting_feedback_json/{user_id}/{product_item_id}/{type}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:getFeedBackJSON,type: null}   

ajax_fitting_feedback_list:
    pattern:  /ajax/fitting_feedback_list/{product_item_id}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:getFeedBackList}
    

ajax_fitting_room_product_recently_tried_on:
    pattern:  /ajax/fitting_room/recently_tried_on/{list_type}/{page_number}/{limit}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:fittingRoomProductsList, page_number: 0, limit: 0}

ajax_user_fitting_room_item_remove:
    pattern:  /ajax/fitting_room_item_remove/{user_id}/{item_id}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:removeFittingRoomItem}  

ajax_user_fitting_room_item_view_update:
    pattern:  /ajax/fitting_room_item_view_update/{user_id}/{item_id}/{view_id}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:itemViewUpdate, view_id: null}  
 
ajax_user_fitting_room_item_ids:
    pattern:  /ajax/fitting_room_item_ids/{user_id}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:getFittingRoomItemIds}

ajax_user_product_item_create:
    pattern:  /ajax/user_product_item/create/{product_item_id}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:addToCloest}
  
ajax_user_product_item_delete:
    pattern:  /ajax/user_product_item/delete/{product_item_id}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:deleteMyClosetAjax}       

ajax_my_closet_delete:
    pattern:  /ajax/products/my_closet/delete/{id}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:deleteMyCloset} 
    
ajax_my_closet_count:
    pattern:  /ajax/products/my_closet/count
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:countMyColoset}
    
  
user_mannequin:
    pattern:  /user/profile/mannequin
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:userMannequin }    
    
#------------------------------------------------------------------
fitting_room_canvas:
    pattern:  /fitting_room/canvas
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:canvas }

fitting_room_canvas_upload:
    pattern:  /fitting_room/canvas_upload
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:userRandomImageUpload }

#-------------------------------------------------------------------
twitter_meta_tags_page:
    pattern:  /free_share/twitter_card_meta_tags/{id}/{file_name}
    defaults: { _controller: LoveThatFitSiteBundle:FittingRoom:twitterCardMetaTags}
 
    
    
    
    


