retailer_login:
    pattern:   /retailer/login
    defaults:  { _controller: LoveThatFitRetailerAdminBundle:Default:retailerlogin }

retailer_login_check:
    pattern:   /retailer/login_check

retailer_logout:
    pattern:   /retailer/logout
    
retailer_admin_dashboard:
    pattern:  /retailer/dashboard
    defaults: { _controller: LoveThatFitRetailerAdminBundle:Default:index }

retailer_admin_product:
    pattern:  /retailer/product/{id}
    defaults: { _controller: LoveThatFitRetailerAdminBundle:Default:retailerProduct }
    
retailer_product:
    pattern:  /retailer/products/{page_number}/{sort}
    defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:index , page_number: 1, sort:id}

retailer_password_reset:
    pattern:  /retailer/password/reset
    defaults: { _controller: LoveThatFitRetailerAdminBundle:Default:resetRetailerPassword }

retailer_password_reset_update:
    pattern:  /retailer/password/reset/update
    defaults: { _controller: LoveThatFitRetailerAdminBundle:Default:retailerPasswordUpdate } 

admin_retailer_product_new:    
    pattern:  /retailer/product/create/new
    defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:retailerProductNew } 
    
retailer_admin_product_create:
    pattern:  /retailer/product/new/create
    defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:retailerProductNewCreate }

retailer_admin_product_detail_show:    
    pattern:  /retailer/product/productdetail/{id}
    defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailShow }

retailer_admin_product_detail_edit:
    pattern:  /retailer/productdetail/{id}/edit
    defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailEdit }

retailer_admin_product_detail_update:
   pattern:  /retailer/productdetail/{id}/update
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailUpdate }

retailer_admin_product_detail_download:
    pattern:  /retailer/productdetail/{id}/download
    defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailDownload }

retailer_admin_product_detail_delete:
    pattern:  /retailer/productdetail/{id}/delete
    defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailDelete }

retailer_admin_product_gender_base_clothing_type:
    pattern:  /retailer/product/gender/clothing_type
    defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:retailerProductGenderBaseClothingType }

retailer_admin_product_get_attribute:
    pattern:  /retailer/product/get/attribute
    defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:retailerProductClothingTypeAttribute }    
#------------------------------------------------------------------------------#
retailer_admin_product_detail_color_image_upload:
   pattern:  /retailer/productdetail/{id}/color/image_upload
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productColorTemporaryImageUpload,_format: json} 

retailer_admin_product_detail_color_create:
   pattern:  /retailer/productdetail/{id}/color/create
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailColorCreate }   

retailer_admin_product_detail_color_add:
   pattern:  /retailer/productdetail/{id}/color/add
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailColorAddNew }
   
retailer_admin_product_detail_color_edit:
   pattern:  /retailer/productdetail/{id}/color/{color_id}/edit
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailColorEdit }
   
retailer_admin_product_detail_color_update:
   pattern:  /retailer/productdetail/{id}/color/{color_id}/update
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailColorUpdate }   
   
retailer_admin_product_detail_color_delete:
   pattern:  /retailer/productdetail/{id}/color/{color_id}/delete
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailColorDelete }  

#--------------------------- Product Sizes --------------       
   
retailer_admin_product_detail_size_edit:
   pattern:  /retailer/productdetail/{id}/size/{size_id}/edit
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailSizeEdit }   
  
retailer_admin_product_detail_size_update:
   pattern:  /retailer/productdetail/{id}/size/{size_id}/update
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailSizeUpdate }   
retailer_admin_product_detail_size_delete:
   pattern:  /retailer/productdetail/{id}/size/{size_id}/delete
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailSizeDelete }   
 
retailer_admin_product_detail_size_measurement_create:
     pattern:  /retailer/product/{id}/size_meaurement/{size_id}/{title}/create
     defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productSizeMeasurementCreate } 

retailer_admin_product_size_measurement_create:
     pattern:  /retailer/product/{id}/sizemeaurement/{size_id}/create
     defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:createProductSizeMeasurement }     

retailer_admin_product_size_measurement_update:
     pattern:  /retailer/product/size_meaurement/{size_id}/{title}/update
     defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productSizeMeasurementupdate }
     
retailer_admin_product_size_measurement_edit:
     pattern:  /retailer/product/{id}/size/{size_id}/meaurement/{measurement_id}/{title}/edit
     defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productSizeMeasurementEdit }

retailer_admin_product_size_measurement_editUpdate:
     pattern:  /retailer/product/{id}/size/{size_id}/meaurement/{measurement_id}/{title}/edit/Update
     defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productSizeMeasurementEditUpdate }
#--------------------------- Product Items --------------       
   
retailer_admin_product_detail_item_edit:
   pattern:  /retailer/productdetail/{id}/item/{item_id}/edit
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailItemEdit }   
  
retailer_admin_product_detail_item_update:
   pattern:  /retailer/productdetail/{id}/item/{item_id}/update
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailItemUpdate } 

retailer_admin_product_detail_item_delete:
   pattern:  /retailer/productdetail/{id}/delete/{item_id}/edit
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailItemDelete }   
retailer_admin_product_detail_item_raw_image_edit:
   pattern:  /retailer/productdetail/{id}/raw_image/{item_id}/edit
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailItemRawImageEdit }   

retailer_admin_product_detail_item_raw_image_download:
   pattern:  /retailer/productdetail/{id}/raw_image/{item_id}/download
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailItemRawImageDownload } 
retailer_admin_product_detail_item_raw_image_delete:   
   pattern:  /retailer/productdetail/{id}/delete/{item_id}/raw_image_delete
   defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productDetailItemRawImageDelete }   
   
#--------------------------- Product Search -----------------------------------#  
retailer_admin_product_search_from:
     pattern:  /retailer/product/searchForm
     defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productSeachForm}
retailer_admin_product_search_result:
     pattern:  /retailer/product/searchResult/{page_number}/{sort}
     defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productSeachResult,page_number: 1, sort:id}
retailer_admin_product_search_category_with_target:
     pattern:  /retailer/product/searchCategory
     defaults: { _controller: LoveThatFitRetailerAdminBundle:RetailerProduct:productSeachCategory}     

     