acme_default:
    pattern:  /acme/default
    defaults: { _controller: AcmeStoreBundle:Default:index }

acme_product_new:
    pattern:  /acme/default/new
    defaults: { _controller: AcmeStoreBundle:Default:new }

acme_product_create:
    pattern:  /acme/default/create
    defaults: { _controller: AcmeStoreBundle:Default:create }

acme_product_edit:
    pattern:  /acme/default/{id}/edit
    defaults: { _controller: AcmeStoreBundle:Default:edit }
    requirements:
        _method:  GET

acme_product_update:
    pattern:  /acme/default/{id}/update
    defaults: { _controller: AcmeStoreBundle:Default:update }
    requirements:
        _method:  POST

acme_merch_ajax_form:
    pattern:  /acme/merch/ajaxform
    defaults: { _controller: AcmeStoreBundle:Merch:ajaxForm }

acme_merch_ajax:
    pattern:  /acme/merch/ajax
    defaults: { _controller: AcmeStoreBundle:Merch:ajax }

acme_merchs:
    pattern:  /acme/merchs
    defaults: { _controller: AcmeStoreBundle:Merch:index }

acme_merch_show:
    pattern:  /acme/merch/{id}/show
    defaults: { _controller: AcmeStoreBundle:Merch:show }

acme_merch_new:
    pattern:  /acme/merch/new
    defaults: { _controller: AcmeStoreBundle:Merch:new }

acme_merch_create:
    pattern:  /acme/merch/create
    defaults: { _controller: AcmeStoreBundle:Merch:create }
    requirements: 
      _method: post 
      
acme_merch_edit:
    pattern:  /acme/merch/{id}/edit
    defaults: { _controller: AcmeStoreBundle:Merch:edit }
    requirements:
        _method:  GET

acme_merch_update:
    pattern:  /acme/merch/{id}/update
    defaults: { _controller: AcmeStoreBundle:Merch:update }
    requirements:
        _method:  POST
        
acme_merch_delete:
    pattern:  /acme/merch/{id}/delete
    defaults: { _controller: AcmeStoreBundle:Merch:delete }
    requirements: 
           _method: POST 

    #-------------------------------------------------------------
acme_store_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index }

productCreate:
    pattern:  /create
    defaults: { _controller: AcmeStoreBundle:Default:create }

productUpdate:
    pattern:  /update/{id}
    defaults: { _controller: AcmeStoreBundle:Default:update, id: 1 }

acme_store_contactinfo:
    resource: "@AcmeStoreBundle/Resources/config/routing/contactinfo.yml"
    prefix:   /