product_intake_product_specs_index:
    pattern:  /product_intake/product_specs/index
    defaults: { _controller: LoveThatFitProductIntakeBundle:ProductSpecs:index }

product_intake_product_specs_csv_upload:
    pattern:  /product_intake/product_specs/csv_upload
    defaults: { _controller: LoveThatFitProductIntakeBundle:ProductSpecs:csvUpload }

product_intake_product_specs_new:
    pattern:  /product_intake/product_specs/new
    defaults: { _controller: LoveThatFitProductIntakeBundle:ProductSpecs:new }
    
product_intake_product_specs_edit:
    pattern:  /product_intake/product_specs/edit/{id}
    defaults: { _controller: LoveThatFitProductIntakeBundle:ProductSpecs:edit }    

product_intake_product_specs_show:
    pattern:  /product_intake/product_specs/show/{id}
    defaults: { _controller: LoveThatFitProductIntakeBundle:ProductSpecs:show }    

product_intake_product_specs_delete:
    pattern:  /product_intake/product_specs/delete/{id}
    defaults: { _controller: LoveThatFitProductIntakeBundle:ProductSpecs:delete }   
    
product_intake_product_specs_update:
    pattern:  /product_intake/product_specs/update/{id}
    defaults: { _controller: LoveThatFitProductIntakeBundle:ProductSpecs:update }     
    