pi_product_fit_points:
    pattern:  /pi/product/{product_id}/fit_points
    defaults: { _controller: LoveThatFitProductIntakeBundle:Product:productFitPoints}

product_intake_product_image_upload_index:
    pattern:  /product_intake/product/image_upload_index
    defaults: { _controller: LoveThatFitProductIntakeBundle:Product:imageUploadIndex}

product_intake_product_image_exists_check:
    pattern:  /product_intake/product/image_exists_check
    defaults: { _controller: LoveThatFitProductIntakeBundle:Product:imageExistsCheck}

pi_product_item_image_data:
    pattern:  /pi/product/item_image_data/{id}
    defaults: { _controller: LoveThatFitProductIntakeBundle:Product:productItemImageData}

product_intake_real_product_image_upload_idex:
    pattern:  /product_intake/product/real_product_image_upload_index
    defaults: { _controller: LoveThatFitProductIntakeBundle:Product:realProductImageUploadIndex}