
pi_ws_specification:
    pattern: /product_intake/product_specification/{brand_name}/{style_id_number}
    defaults: { _controller: LoveThatFitProductIntakeBundle:Service:getProductSpecification}
    requirements:
        _method:  get

pi_ws_product_detail:
    pattern: /pi/ws/product_detail
    defaults: { _controller: LoveThatFitProductIntakeBundle:Service:productDetail}
    
pi_ws_save_product:
    pattern: /pi/ws/save_product
    defaults: { _controller: LoveThatFitProductIntakeBundle:Service:saveProduct} 
    
pi_ws_existing_product_specification:
    pattern: /product_intake/existing_product_specification/{brand_name}/{style_id_number}
    defaults: { _controller: LoveThatFitProductIntakeBundle:Service:getExistingProductSpecification}
    requirements:
        _method:  get    
 

pi_ws_product_image_upload:
    pattern: /product_intake/product_image_upload
    defaults: { _controller: LoveThatFitProductIntakeBundle:Service:ImageUploadproductSizeItem}
    requirements:
        _method:  post  
        
pi_ws_item_image_exists:
    pattern: /pi/ws/item_image_exists/{file_name}
    defaults: { _controller: LoveThatFitProductIntakeBundle:Service:itemImageExists}
    requirements:
        _method:  get
        