ws_interface_index:
    pattern:  /admin/ws_interface/index
    defaults: { _controller: LoveThatFitWebServiceBundle:WSInterface:index}

ws_interface_user:
    pattern:  /ws_interface/user/{email}
    defaults: { _controller: LoveThatFitWebServiceBundle:WSInterface:user}

braintree_test_transaction:
    pattern: /ws/braintree_test_transaction
    defaults: { _controller: LoveThatFitWebServiceBundle:WSInterface:brainTreeTestTransaction}

braintree_save_card:
      pattern: /ws/braintree_save_card
      defaults: { _controller: LoveThatFitWebServiceBundle:WSInterface:brainTreeSaveCard}
