ws_foo:
    pattern:  /ws/foo
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:foo }

ws_user_login:
    pattern:  /ws/login
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:login }

nws_user_detail:
    pattern:  /ws/user_detail
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:detail }
    
ws_user_email_exists:
    pattern:  /ws/user_email_exists
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:emailExists }

ws_user_registration:
    pattern:  /ws/user_registration
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:registration }

ws_user_measurement_update:
    pattern:  /ws/user_measurement_update
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:measurementUpdate }

ws_size_charts:
    pattern:  /ws/size_charts
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:sizeCharts }

ws_user_image_uploader:
    pattern:  /ws/user_image_uploader
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:imageUploader }

nws_user_password_change:
    pattern:  /ws/user_password_change
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:passwordChange }

nws_user_forgot_password:
    pattern:  /ws/user_forgot_password
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:forgotPassword }

nws_user_forgot_password_token_auth:
    pattern:  /ws/user_forgot_password_token_auth
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:forgotPasswordTokenAuth }

nws_user_forgot_password_update:
    pattern:  /ws/user_forgot_password_update
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:forgotPasswordUpdate }

ws_user_profile_update:
    pattern:  /ws/user_profile_update
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:profileUpdate }

ws_user_admin_list:
    pattern:  /ws/user_admin_list
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:userAdminList }
#------------------------------------------------------------------------------------

nws_products:
    pattern:  /ws/products
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:products }

nws_product_detail:
    pattern:  /ws/product_detail
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:productDetail }

ws_product_list:
    pattern:  /ws/product_list
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:productList }

ws_product_like_default_item:
    pattern:  /ws/product_like_default_item
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:productLikeDefaultItem }

ws_product_like:
    pattern:  /ws/product_like
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:productLike }

ws_user_liked_products:
    pattern:  /ws/user_liked_products
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:userLikedProducts }
    
nws_brand_retailer:
    pattern:  /ws/brand_retailer
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:brandRetailer }
