ws_user_login:
    pattern:  /ws/login
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:login }

ws_user_email_exists:
    pattern:  /ws/user_email_exists
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:emailExists }

ws_user_registration:
    pattern:  /ws/user_registration
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:registration }

ws_size_charts:
    pattern:  /ws/size_charts
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:sizeCharts }

ws_image_uploader:
    pattern:  /ws/image_uploader
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:imageUploader }
