ws_change_user_status:
    pattern:  /ws/change_user_status/{token}/{status}
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:changeUserStatus }

ws_send_push_notification:
    pattern:  /ws/send_push_notification
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:sendPushNotification }

ws_send_push_notification_clothing_type:
   pattern:  /ws/send_push_notification_clothing_type
   defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:sendPushNotificationClothingType }

ws_user_login:
    pattern:  /ws/login
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:login }

ws_user_logout:
    pattern: /ws/logout
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:logout }

nws_user_detail:
    pattern:  /ws/user_detail
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:detail }
    
ws_user_email_exists:
    pattern:  /ws/user_email_exists
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:emailExists }

ws_user_registration:
    pattern:  /ws/user_registration
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:registration }

ws_user_measurement_update:
    pattern:  /ws/user_measurement_update
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:measurementUpdate }

ws_size_charts:
    pattern:  /ws/size_charts
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:sizeCharts }

ws_user_image_uploader:
    pattern:  /ws/user_image_uploader
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:imageUploader }

ws_user_file_uploader:
    pattern:  /ws/user_file_uploader
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:fileUploader }

nws_user_password_change:
    pattern:  /ws/user_password_change
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:passwordChange }

nws_user_forgot_password:
    pattern:  /ws/user_forgot_password
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:forgotPassword }

nws_web_user_forgot_password:
    pattern:  /nws/web_user_forgot_password
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:forgotPasswordWeb }

nws_user_forgot_password_token_auth:
    pattern:  /ws/user_forgot_password_token_auth
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:forgotPasswordTokenAuth }

nws_user_forgot_password_update:
    pattern:  /ws/user_forgot_password_update
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:forgotPasswordUpdate }

ws_user_profile_update:
    pattern:  /ws/user_profile_update
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:profileUpdate }

ws_user_admin_list:
    pattern:  /ws/user_admin_list
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:userAdminList }

ws_user_feedback_add:
    pattern:  /ws/user_feedback_add
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:feedbackAdd }

ws_user_default_values:
    pattern:  /ws/user_default_values
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:defaultValues}

ws_selfieshare_create:
    pattern:  /ws/selfieshare/create
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:selfieshareCreate}

ws_selfieshare_create_v3:
    pattern:  /ws/selfieshare/create_v3
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:selfieshareCreateV3}

nws_web_invitefriend_create:
    pattern:  /nws/invitefriend/create
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:invitefriendCreate}

nws_web_register_male_users:
    pattern:  /nws/registermaleusers/create
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:registermaleusersCreate}

#------------------------------------------------------------------------------------

nws_products:
    pattern:  /ws/products
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:products }

nws_product_detail:
    pattern:  /ws/product_detail
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:productDetail }

ws_product_list:
    pattern:  /ws/product_list
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:productList }

ws_product_like_default_item:
    pattern:  /ws/product_like_default_item
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:productLikeDefaultItem }

ws_product_like:
    pattern:  /ws/product_like
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:productLike }

ws_user_liked_products:
    pattern:  /ws/user_liked_products
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:userLikedProducts }
    
nws_brand_retailer:
    pattern:  /ws/brand_retailer
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:brandRetailer }
#--------------------------------------------------------------
ws_misc_faq:
    pattern:  /ws/misc_faq
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:faq}

ws_misc_banner:
    pattern:  /ws/misc_banner
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:banner}

ws_build_config:
    pattern:  /ws/build_config
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:buildConfig}


ws_support_task_log_add:
    pattern:  /ws/support_task_log/add
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:logTask}
#-------------------------Shopping Cart Routes-------------------------------------

#Add Single Item to Cart
ws_cart_item_add_to_cart:
    pattern:  /ws/add_item_to_cart
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:addItemToCart}

#Add multiple Item to Cart
ws_cart_multiple_items:
    pattern:  /ws/add_items_to_cart
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:addItemsToCart}

#Remove User Cart
ws_remove_user_cart:
    pattern:  /ws/remove_user_cart
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:removeUserCart}

#remove single item from user cart
ws_remove_user_cart_item:
    pattern:  /ws/remove_user_item
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:removeUserItem}

#Show User Cart
ws_show_user_cart:
    pattern:  /ws/show_user_cart
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:showUserCart}

#-------------------------Shopping Cart Routes-------------------------------------

#-------------------------Caliboration Image Approved/Reject Routes-------------------------------------

ws_image_approval:
    pattern:  /ws/image_approval
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:imageApproval}

ws_events_list:
    pattern:  /ws/events_list
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:eventsList}


ws_feedback_category_list:
    pattern:  /ws/feedback_category_list
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:feedbackCategoryList}

#// APP 3.0-------------------------------------------------------
nws_brand_banner:
    pattern:  /nws/brand_banner
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCategory:getBannerBrandProducts}

nws_filter_banner:
    pattern:  /nws/filter_banner
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCategory:getBannerFilterProducts}

nws_banner_category:
    pattern:  /nws/banner_category
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCategory:getBannerCategoryList}

nws_product_list:
    pattern:  /nws/product_list
    defaults: { _controller: LoveThatFitWebServiceBundle:ProductList:getCategoryProductsList}  
    
nws_product_list_banner:
    pattern:  /nws/product_list_with_banner
    defaults: { _controller: LoveThatFitWebServiceBundle:ProductList:getCategoryProductsListBanner}
    
nws_product_detail_with_images:
    pattern:  /nws/product_detail_with_images
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:productDetailWithImages } 
    
nws_show_user_cart:
    pattern:  /nws/show_user_cart
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:showUserCartWithNameDescription}

#Add Single Item to Cart
nws_cart_single_item:
    pattern:  /nws/add_item_to_cart
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:addItemToCartNew}

#Add multiple Item to Cart
nws_cart_multiple_items:
    pattern:  /nws/add_items_to_cart
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:addItemsToCartNew}

#--------------------------------------Wishlist
#show wishlist
nws_show_user_wishlist:
    pattern:  /nws/show_user_wishlist
    defaults: { _controller: LoveThatFitWebServiceBundle:WSWishlist:showUserWishlistWithNameDescription}

#Add Single Item to Wishlist
nws_wishlist_item_add_to_wishlist:
    pattern:  /nws/add_item_to_wishlist
    defaults: { _controller: LoveThatFitWebServiceBundle:WSWishlist:addItemToWishlistNew}

#remove single item from user wishlist
nws_remove_user_wishlist_item:
    pattern:  /nws/remove_user_item
    defaults: { _controller: LoveThatFitWebServiceBundle:WSWishlist:removeUserItem}


ws_get_braintree_authtoken:
   pattern:  /ws/get_braintree_authtoken
   defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:getAuthToken}

ws_braintree_payment:
  pattern:  /ws/braintree_payment
  defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:makePayment}

nws_save_user_look:
    pattern: /nws/save_user_look
    defaults: { _controller: LoveThatFitWebServiceBundle:WSSaveLook:saveLook}

nws_get_user_looks:
    pattern: /nws/get_user_looks
    defaults: { _controller: LoveThatFitWebServiceBundle:WSSaveLook:getUserLooks}

nws_remove_user_look:
    pattern: /nws/remove_user_look
    defaults: { _controller: LoveThatFitWebServiceBundle:WSSaveLook:removeUserLook}

nws_add_update_fitting_room:
    pattern:  /nws/add_update_fitting_room
    defaults: { _controller: LoveThatFitWebServiceBundle:FittingRoom:addUpdateToFittingRoom}

nws_delete_fitting_room_item:
    pattern:  /nws/delete_fitting_room_item
    defaults: { _controller: LoveThatFitWebServiceBundle:FittingRoom:deleteToFittingRoom}

nws_get_all_fitting_room:
    pattern:  /nws/get_all_fitting_room
    defaults: { _controller: LoveThatFitWebServiceBundle:FittingRoom:getAllFittingRoom}

nws_add_update_fitting_room_items:
    pattern:  /nws/add_update_fitting_room_items
    defaults: { _controller: LoveThatFitWebServiceBundle:FittingRoom:addUpdateToFittingRoomItems}

ws_braintree_payment_and_create_order:
   pattern: /ws/braintree_payment_and_create_order
   defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:brainTreePaymentWithAddItemToCart}

ws_get_applicablefnf_user:
   pattern: /ws/get_applicablefnf_user
   defaults: { _controller: LoveThatFitAdminBundle:FNFUser:getApplicableFNFUser}

nws_get_applicablefnf_user:
   pattern: /nws/get_applicablefnf_user
   defaults: { _controller: LoveThatFitAdminBundle:FNFUser:nwsGetApplicableFNFUser}

ws_braintree_processuser_transaction:
    pattern: /ws/braintree_processuser_transaction
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:brainTreeProcessTransaction}

nws_braintree_processuser_transaction:
    pattern: /nws/braintree_processuser_transaction
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:nwsBrainTreeProcessTransaction}

nws_braintree_save_credit_card:
    pattern: /nws/braintree_save_credit_card
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:nwsBraintreeSaveCreditCard}

nws_braintree_get_all_credit_cards:
    pattern: /nws/braintree_get_credit_cards
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:nwsBraintreeGetCreditCards}

nws_braintree_delete_credit_card:
    pattern: /nws/braintree_delete_credit_card
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:nwsBraintreeDeleteCreditCard}

nws_braintree_update_credit_card:
    pattern: /nws/braintree_update_credit_card
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:nwsBraintreeUpdateCreditCard}

ws_get_braintree_client_token:
    pattern: /ws/get_braintree_client_token
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:brainTreeGetClientToker}

ws_order_detail:
   pattern: /ws/order_detail
   defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:orderDetail}

ws_basic_order_info:
   pattern: /ws/basic_order_info
   defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:basicOrderInfo}

nws_save_user_shipping_address:
  pattern: /nws/save_user_shipping_address
  defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:saveUserShippingAddress}

nws_delete_user_address:
  pattern: /nws/delete_user_address
  defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:deleteUserShippingOrBillingAddress}

nws_save_user_billing_address:
  pattern: /nws/save_user_billing_address
  defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:saveUserBillingAddress}

nws_get_all_user_saved_addresses:
  pattern: /nws/get_all_user_saved_addresses
  defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:getAllUserSavedAddresses}

nws_get_shipping_methods:
  pattern: /nws/get_shipping_methods
  defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:getShippingMethods}

nws_get_all_user_saved_addresses_and_rates:
  pattern: /nws/get_all_user_saved_addresses_rates
  defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:getAllUserSavedAddressesWithRates}

nws_address_verficiation:
  pattern: /nws/address_verification
  defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:addressVerification}

nws_get_shipping_rates:
  pattern: /nws/get_shipping_rates
  defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:getShippingRates}

ws_shop_the_look:
    pattern:  /ws/shop_the_look
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:shopTheLook }


nws_shop_the_look:
    pattern:  /nws/shop_the_look
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:shopTheLookV3 }

ws_brand_n_deviceconfig:
    pattern:  /ws/brand_n_deviceconfig
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:brandAndDevice }

ws_brand_retailer_big:
    pattern:  /ws/brand_retailer_big
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:brandRetailerBig }

nws_selfieshare_create:
    pattern:  /nws/selfieshare/create
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:selfieshareCreateNew}

ws_marketing_tiles:
    pattern:  /ws/marketing_tiles
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:marketingTiles}

new_register_device_token:
    pattern: /nws/register_device_token
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:regsiterUserDeviceToken}

mcp_get_user_mask_marker_details:
    pattern: /mcp/get_user_mask_marker_details
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:userMaskMarkerdetail}

render_user_image:
    pattern: /render/image/{ref}
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:renderImageBySessionId, ref: null}

render_user_avatar:
    pattern: /render/avatar/{ref}
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:renderAvatarBySessionId, ref: null}

nws_get_brand_style:
    pattern:  /nws/get_brand_style
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCategory:getBrandStyleList}

nws_search_brand_style:
    pattern:  /nws/search_brand_style
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:searchBrandStyle }

mcp_save_marker:
    pattern: /mcp/save_marker
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:mcpSaveMarker }

nws_get_order_sales_tax_user:
   pattern: /nws/get_order_sales_tax_user
   defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:getOrderSalesTaxUser}

mcp_save_marker_image:
    pattern: /mcp/save_marker_image
    defaults: { _controller: LoveThatFitWebServiceBundle:WSMisc:archiveImageUpdateMcp}
   
mcp_reject_user_image:
    pattern: /mcp/mcp_reject_user_image
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:pendingUsersRevertedImage} 

mcp_get_user_image:
    pattern: /mcp/mcp_get_user_image
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:userOriginalImage}

mcp_approve_complete:
    pattern: /mcp/mcp_approve_complete
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:mcpArchiveToLive}

mcp_get_user_save:
    pattern: /mcp/mcp_get_user_save
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:mcpArchiveSaveMarker}

ws_email_order_detail_show:
    pattern:  /ws/order/detail/{order_number}/show
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:showEmailDetail}

nws_update_primary_email:
    pattern: /nws/update_primary_email
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:nwsUpdatePrimaryEmail}

nws_web_user_registration:
    pattern: /nws/web_user_registration
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:registrationFromWeb }

nws_render_iphone_file:
    pattern: /apple-app-site-association
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:renderIphoneFile }

appuser_check_exist_email:
    pattern:   appuser/check_exist_email
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:checkEmailEixstFunc } 

appuser_male_invite_friend_email:
    pattern:   appuser/male_invite_friend_email
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:invitefriendformaleCreate }

appuser_invite_friend:
    pattern:   /appuser/invite_friend_text
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:inviteFriendCreateText }

#update Single Item to Cart
nws_update_cart_single_item:
    pattern:  /nws/update_item_to_cart
    defaults: { _controller: LoveThatFitWebServiceBundle:WSCart:updateItemToCartNew}   

appuser_male_check_exist_email:
    pattern:   appuser/male_check_exist_email
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:checkMaleEmailEixstFunc }  