ws_foo:
    pattern:  /ws/foo
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:foo }

ws_user_login:
    pattern:  /ws/login
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:login }

nws_user_detail:
    pattern:  /ws/user_detail
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:detail }
    
ws_user_email_exists:
    pattern:  /ws/user_email_exists
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:emailExists }

ws_user_registration:
    pattern:  /ws/user_registration
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:registration }

ws_size_charts:
    pattern:  /ws/size_charts
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:sizeCharts }

ws_user_image_uploader:
    pattern:  /ws/user_image_uploader
    defaults: { _controller: LoveThatFitWebServiceBundle:WSUser:imageUploader }


#------------------------------------------------------------------------------------

nws_products:
    pattern:  /ws/products
    defaults: { _controller: LoveThatFitWebServiceBundle:WSProduct:products }
