wst_login:
    pattern:  /web_service_test/login
    defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:login }
  
wst_registration_create:
   pattern:  /web_service_test/register
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:registrationCreate}

wst_edit_profile:
   pattern:  /web_service_test/edit_profile
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:editProfile}   

wst_measurement_edit:
   pattern:  /web_service_test/measurement_edit
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:measurementEdit}
    
wst_user_profile:
   pattern:  /web_service_test/user_profile
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:userProfile}    
   
avatarUpload:
   pattern:  /web_service_test/upload_avatar
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:avatarUpload} 

wst_image_upload:
   pattern:  /web_service_test/image_upload
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:imageUpload}

wst_iphone_shoulder_outseam:
   pattern:  /web_service_test/iphone_shoulder_outseam
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:shoulderOutseamEdit}   
 
wst_change_password:
   pattern:  /web_service_test/change_password
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:changePassword}
  
wst_forget_password:
    pattern:  /web_service_test/forget_password
    defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:forgetPassword }

wst_check_token__forget_password:
    pattern:  /web_service_test/check_token_forget_password
    defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:checkTokenforgetPassword }

wst_update__forget_password:
    pattern:  /web_service_test/check_update_password
    defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:updateForgetPassword }  

wst_check_email:
   pattern:  /web_service_test/checkemail
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:emailCheck}   
   
#----------------------------- user & product -------------------------------



#----------------------------------------------------
constantValue:
   pattern:  /web_service_test/constant_values
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:ConstantValues}
   
registrationSizechart:
   pattern:  /web_service_test/registration_sizechart
   defaults: { _controller: LoveThatFitWebServiceBundle:WSTest:sizeChartForReg}

   
   

