
map:
  neck:  
   axis: x 
   type: single
   segments: 
     s1:
       a: 6
       b: 64  
  bust: 
    axis: x
    type: single
    segments: 
      s1:  
        a: 17
        b: 53    
  shoulder_across_front: 
    axis: x 
    type: single
    segments: 
      s1:
        a: 7
        b: 63            
  waist: 
    axis: x 
    type: single
    segments: 
      s1:
        a: 18
        b: 52  

  belt_waist: 
    axis: x 
    type: single
    segments: 
      s1:
        a: 19
        b: 51 
  abdomen: 
    axis: x 
    type: single
    segments: 
      s1:
        a: 19
        b: 51 
  low_hip: 
    axis: x 
    type: single 
    segments: 
      s1: 
        a: 21
        b: 49        
  high_hip: 
    axis: x 
    type: single 
    segments: 
      s1: 
        a: 20
        b: 50
data:
    laurie:
       [[1780,540],[1950,696],[1980,763],[1991,818],[1950,852],[1913,956],[1921,1015],[2153,1145],[2333,1520],[2392,1858],[2418,2474],[2340,2839],[2327,2668],[2336,2462],[2218,1950],[2166,1520],[2151,1423],[2099,1472],[2073,1883],[2110,2026],[2154,2164],[2177,2314],[2158,2758],[2095,3194],[2086,3374],[2104,3711],[2058,4227],[2151,4641],[2101,4700],[1980,4641],[1952,4374],[1945,4227],[1870,3711],[1854,3375],[1828,2758],[1804,2600],[1787,2758],[1748,3375],[1752,3711],[1705,4227],[1702,4361],[1676,4639],[1568,4702],[1518,4639],[1590,4227],[1520,3711],[1531,3375],[1523,3194],[1453,2758],[1436,2314],[1455,2164],[1492,2026],[1525,1883],[1477,1472],[1446,1423],[1420,1523],[1386,1973],[1271,2500],[1267,2707],[1264,2826],[1189,2500],[1208,1909],[1258,1522],[1429,1150],[1676,1015],[1676,956],[1631,852],[1594,822],[1624,763],[1627,696]] 
       #[[478,144],[524,186],[532,204],[535,219],[524,228],[514,256],[516,272],[578.5,307],[627,408],[643,499],[650,665],[629,763.5],[625.5,717.5],[628,662],[596,524],[582,408],[578,382],[564,395],[557,506],[567,544.5],[579,581.5],[585,622],[580,741.5],[563,859],[560.5,907.5],[565.5,998.5],[553,1137.5],[578,1249],[564.5,1265],[532,1249],[524.5,1177],[522.5,1137.5],[502.5,998.5],[498,908],[491,741.5],[484.5,699],[480,741.5],[469.5,908],[470.5,998.5],[458,1137.5],[457,1173.5],[450,1248.5],[421,1265.5],[407.5,1248.5],[427,1137.5],[408,998.5],[411,908],[409,859],[390,741.5],[385.5,622],[390.5,581.5],[400.5,544.5],[409.5,506],[396.5,395],[388,382],[381,409],[372,530],[341,672],[340,728],[339,760],[319,672],[324,513],[337.5,408.5],[383.5,308.5],[450,272],[450,256],[438,228],[428,220],[436,204],[437,186]]
       