
f:
  measurements:
    bra_size: "34 b"
    body_shape: hourglass
    body_type: regular
    weight: 114
    height: 67.5
    waist:  25
    belt: 0
    hip:  35.6
    bust: 33.7
    chest:  33.7
    arm:  0
    inseam: 31
    shoulder_height:  144.62
    outseam:  0
    sleeve: 26.8
    neck: 12.4  
    thigh: 20.8
    center_front_waist: 16.2
    shoulder_across_front: 13.8
    shoulder_across_back: 14.4
    bicep: 8.4
    tricep: 9.8
    wrist: 5.8
    back_waist: 18.2
    waist_hip: 9.8
    knee: 13.5
    calf: 12.7
    ankle: 8.7
    shoulder_width: 0
    bust_height: 0
    waist_height: 0
    hip_height: 304.53
    bust_width: 0
    waist_width: 0
    hip_width: 0
  image:
    url: 'f_cropped.png'
    device_type: iphone6
    px_inch_ratio: 7.797
  mask:
    svg_path: M138.28171,73.39271c-1.976,9.6856 -1.395,11.50975 -0.795,13.33901c-3,-1.08633 -3.424,8.24123 -3.118,9.61483c1.774,7.86295 5.126,7.48208 5.327,7c0.689,1.99766 2.727,11.02562 3.736,13.05849c0.151,3.6343 1.007,14.59941 -1.217,16.6466c-5.672,5.1851 -8.994,8.36561 -27.605,14.59521c-10.398,3.89515 -9.6112,11.7205 -13.6912,40.33376c-0.216,3.90176 -6.055,20.38468 -8.413,37.58873c-2.808,27.08888 -6.36,24.14654 -6.925,75.28653c-4.963,14.22463 -10.1028,35.65178 2.4782,45.58943c1.369,1.25693 21.389,2.6166 9.624,-21.33106c1.121,-2.28162 0.682,-11.01757 -1.992,-22.25947c0.415,-1.51778 6.3158,-21.70877 15.4378,-73.41559c2.328,-21.21368 2.114,-16.7283 3.025,-25.05241c0.314,-1.84687 4.0642,-29.72367 5.7202,-29.72367c0.797,0.06384 2.999,9.91186 3.342,14.69412c2.861,20.2154 3.593,24.47278 3.716,40.66315c-0.505,9.4985 -3.786,11.96596 -5.778,18.27371c-2.22,6.26042 -2.505,9.62174 -5.041,24.32845c-1.527,18.02623 -1.925,14.90753 -2.58,31.91567c1.261,19.03992 -1.9314,8.33854 1.3666,35.81484c5.515,29.84047 6.767,32.15982 8.329,57.97086c-0.007,11.89128 0.913,3.53522 -0.176,20.83393c-1.268,20.66006 1.378,21.35975 2.012,31.85873c3.1,25.60412 6.19205,28.70526 7.94405,43.10159c0.795,9.00431 1.33301,4.00558 0.98901,20.12991c-0.876,10.27775 0.27834,16.57647 -1.59366,21.37855c-1.229,4.69972 -5.32,16.5426 13.567,16.5066c2.331,0.03962 8.557,11.5192 10.633,-9.5828c0.266,-6.03479 -7.73925,-36.87229 -8.88025,-41.30016c1.709,-28.90383 -1.60975,-28.91388 0.19125,-51.24911c0.194,-7.36656 1.9231,-31.62175 1.6961,-37.4001c3.125,-14.74303 2.7263,-35.23799 4.3163,-72.2315c0.005,-8.07868 0.8696,-24.78409 3.3306,-24.78409c2.362,0 2.9096,14.03888 3.3416,25.23676c0.857,37.02653 1.7043,58.2185 4.6423,72.61923c-0.098,5.65617 1.7641,31.61718 1.7871,38.95623c2.082,22.42548 3.73125,19.3673 5.76125,48.37128c-1.328,4.28808 -3.42825,36.11127 -3.80125,42.24953c1.893,21.066 7.248,10.17415 9.014,10.11032c17.533,0.059 15.76,-6.04352 13.963,-10.5c-1.758,-4.845 -5.12566,-14.81653 -5.44666,-24.89616c-0.564,-16.02417 -0.52194,-14.56947 0.34906,-23.59799c1.535,-14.53281 2.816,-20.09873 5.754,-45.46071c0.711,-10.72461 0.713,-11.95842 -0.619,-32.57775c-1.315,-16.86396 -0.391,-9.09784 -0.637,-20.64352c1.457,-25.89248 3.677,-25.42866 8.85,-55.12275c3.746,-27.24186 1.0166,-16.05338 1.9556,-34.78072c-0.762,-17.15123 -1.44,-17.57985 -2.759,-35.40357c-2.628,-14.66379 -0.273,-16.84869 -2.694,-22.84606c-2.164,-6.44093 -6.931,-7.44031 -7.543,-16.72418c-0.32,-16.48644 5.263,-20.29665 8.201,-40.19177c0.596,-4.96828 2.037,-16.1578 2.68,-16.1578c1.287,-0.0011 -3.7788,17.25573 -3.6308,19.14662c0.838,8.38025 0.845,9.66814 3.486,31.0359c7.926,51.71453 16.6978,71.98366 17.1518,73.4321c-2.94,11.01628 -2.773,23.28524 -2.123,25.77158c-8.449,23.59766 9.424,25.06022 11.18,23.8154c14.952,-10.22051 3.9808,-36.34804 0.9668,-50.55726c-0.274,-51.38213 -5.503,-39.14892 -8.071,-65.77442c-3.115,-17.23267 -1.903,-40.21449 -2.426,-44.13166c-3.579,-28.75744 -7.2538,-38.67745 -19.0068,-42.34257c-19.662,-6.25382 -14.636,-7.59832 -20.896,-12.63373c-2.991,-2.26071 -1.457,-12.47818 -1.633,-15.96389c1.111,-1.80835 4.537,-9.33427 4.769,-10.21258c1.899,1.97344 2.721,-7.31828 3.108,-8.52348c2.675,-8.54865 0.753,-9.39958 0.399,-9.14864c3.409,-6.33417 -3.823,-13.1825 -4.168,-14.7465c-3.816,-14.60985 -20.406,-14.61389 -20.406,-14.61389c-17.327,0 -20.159,13.5925 -20.475,14.61389z 
    mask_x: 157
    mask_y: 534
    rect_x: 32
    rect_y: 52.5
    rect_height: 
    rect_width: 
    marker_json: 
    default_marker_json:
    default_marker_svg: M139.4159,74.67562c-1.976,9.6856 0.605,14.37872 1.205,16.20798c-3,-1.08633 -0.924,5.75743 -0.618,7.13103c1.774,7.86295 3.626,7.09691 3.827,6.61483c0.689,1.99766 2.727,12.52562 3.736,14.55849c0.151,3.6343 -0.993,13.09941 -3.217,15.1466c-5.672,5.1851 -14.494,5.36561 -33.105,11.59521c-10.398,3.89515 -9.6112,23.2205 -13.6912,51.83376c-0.216,3.90176 -1.555,11.88468 -3.913,29.08873c-2.808,27.08888 -3.86,21.14654 -4.425,72.28653c-4.963,14.22463 -8.1028,28.65178 4.4782,38.58943c1.369,1.25693 16.889,12.6166 5.124,-11.33106c1.121,-2.28162 5.182,-16.01757 2.508,-27.25947c0.415,-1.51778 1.8158,-16.70877 10.9378,-68.41559c2.328,-21.21368 2.114,-20.7283 3.025,-29.05241c0.314,-1.84687 2.0642,-18.72367 3.7202,-18.72367c0.797,0.06384 1.499,8.91186 1.842,13.69412c2.861,20.2154 4.093,18.97278 4.216,35.16315c-0.505,9.4985 -1.286,10.46596 -3.278,16.77371c-2.22,6.26042 -2.505,6.12174 -5.041,20.82845c-1.527,18.02623 -1.425,19.40753 -2.08,36.41567c1.261,19.03992 1.0686,9.33854 4.3666,36.81484c5.515,29.84047 6.767,31.65982 8.329,57.47086c-0.007,11.89128 0.413,0.03522 -0.676,17.33393c-1.268,20.66006 -1.122,21.85975 -0.488,32.35873c3.1,25.60412 4.69205,31.20526 6.44405,45.60159c0.795,9.00431 2.33301,10.50558 1.98901,26.62991c-0.876,10.27775 0.27834,8.07647 -1.59366,12.87855c-1.229,4.69972 -14.82,22.0426 4.067,22.0066c2.331,0.03962 11.557,-0.898 13.633,-22c0.266,-6.03479 -0.73925,-8.45509 -1.88025,-12.88296c1.709,-28.90383 3.39025,-49.91388 5.19125,-72.24911c0.194,-7.36656 -0.5769,-29.12175 -0.8039,-34.9001c3.125,-14.74303 3.7263,-35.23799 5.3163,-72.2315c0.005,-8.07868 -1.1304,-24.28409 1.3306,-24.28409c2.362,0 0.9096,13.03888 1.3416,24.23676c0.857,37.02653 2.2043,57.7185 5.1423,72.11923c-0.098,5.65617 -0.7359,27.61718 -0.7129,34.95623c2.082,22.42548 3.23125,43.3673 5.26125,72.37128c-1.328,4.28808 -1.42825,6.69407 -1.80125,12.83233c1.893,21.066 12.748,22.09135 14.514,22.02752c17.533,0.059 4.76,-17.54352 2.963,-22c-1.758,-4.845 -1.12566,-2.81653 -1.44666,-12.89616c-0.564,-16.02417 1.97806,-17.56947 2.84906,-26.59799c1.535,-14.53281 2.816,-20.09873 5.754,-45.46071c0.711,-10.72461 0.713,-11.95842 -0.619,-32.57775c-1.315,-16.86396 -0.391,-5.59784 -0.637,-17.14352c1.457,-25.89248 3.177,-27.92866 8.35,-57.62275c3.746,-27.24186 3.5166,-18.05338 4.4556,-36.78072c-0.762,-17.15123 -0.94,-18.57985 -2.259,-36.40357c-2.628,-14.66379 -2.773,-14.84869 -5.194,-20.84606c-2.164,-6.44093 -2.431,-7.44031 -3.043,-16.72418c-0.32,-16.48644 1.263,-15.29665 4.201,-35.19177c0.596,-4.96828 1.037,-13.6578 1.68,-13.6578c1.287,-0.0011 3.7212,16.75573 3.8692,18.64662c0.838,8.38025 0.345,7.66814 2.986,29.0359c7.926,51.71453 10.6978,66.98366 11.1518,68.4321c-2.94,11.01628 1.727,24.78524 2.377,27.27158c-8.449,23.59766 2.924,12.64302 4.68,11.3982c14.952,-10.22051 8.9808,-24.43084 5.9668,-38.64006c-0.274,-51.38213 -2.003,-45.64892 -4.571,-72.27442c-3.115,-17.23267 -3.403,-25.21449 -3.926,-29.13166c-3.579,-28.75744 -3.7538,-48.17745 -15.5068,-51.84257c-19.662,-6.25382 -26.136,-6.59832 -32.396,-11.63373c-2.991,-2.26071 -2.957,-11.47818 -3.133,-14.96389c1.111,-1.80835 3.537,-13.83427 3.769,-14.71258c1.899,1.97344 3.221,-5.31828 3.608,-6.52348c2.675,-8.54865 -0.247,-7.39958 -0.601,-7.14864c3.409,-6.33417 1.677,-14.6825 1.332,-16.2465c-3.816,-14.60985 -20.406,-14.61389 -20.406,-14.61389c-17.327,0 -20.159,13.5925 -20.475,14.61389z
    default_user: true

m:
  measurements:
    body_shape: athletic
    body_type: regular
    weight: 60
    height: 60
    waist:  60
    belt: 60
    hip:  60
    chest:  60
    arm:  60
    inseam: 60
    shoulder_height:  60
    outseam:  60
    sleeve: 60
    neck: 60
    thigh: 60
    center_front_waist: 60
    shoulder_across_front: 60
    shoulder_across_back: 60
    bicep: 60
    tricep: 60
    wrist: 60
    back_waist: 60
    waist_hip: 60
    knee: 60
    calf: 60
    ankle: 60
    shoulder_width: 60
    bust_height: 60
    waist_height: 60
    hip_height: 60
    bust_width: 60
    waist_width: 60
    hip_width: 60
  image:
    url:  'images/man.png'
    device_type: iphone6
  mask:
    svg_path: M102.392,24.025c0,0,16.59-1.163,20.406,12.111c0.345,1.421,2.077,9.006-1.332,14.761c0.354-0.228,3.276-1.272,0.601,6.495c-0.387,1.095-1.709,7.72-3.608,5.927c-0.232,0.798-2.658,11.141-3.769,12.784c0.176,3.167,0.142,12.125,3.133,14.179c6.26,4.575,9.329,4.888,28.991,10.57c11.753,3.33,11.383,22.141,14.962,48.269c0.523,3.559,0.811,10.811,3.926,26.468c2.568,24.191,4.297,18.982,4.571,65.666c3.014,12.91,12.935,25.821-2.017,35.107c-1.756,1.131-13.129,11.084-4.68-10.356c-0.65-2.259-5.317-14.769-2.377-24.778c-0.454-1.316-6.086-15.189-14.012-62.175c-2.641-19.414-2.148-18.767-2.986-26.381c-0.148-1.718-3.127-21.49-4.414-21.489c-0.643,0-1.084,7.895-1.68,12.409c-2.938,18.076-4.521,16.995-4.201,31.974c0.612,8.435,0.879,9.343,3.043,15.195c2.421,5.449,2.566,5.617,5.194,18.94c1.319,16.194,1.497,17.492,2.259,33.075c-0.939,17.015-0.982,13.214-4.728,37.965c-5.173,26.979-6.212,28.829-7.669,52.354c0.246,10.49-0.678,0.254,0.637,15.576c1.332,18.734,1.33,19.855,0.619,29.599c-2.938,23.043-4.219,28.1-5.754,41.304c-0.871,8.203-0.987,9.607-0.423,24.166c0.321,9.158,0.259,7.315,2.017,11.717c1.797,4.049,14.57,18.456-2.963,18.397c-1.766,0.058-12.621,2.644-14.514-18.422c0.373-5.577,0.984-7.763,2.312-11.659c-2.03-26.352-3.69-45.379-5.772-65.754c-0.023-6.668,1.364-26.621,1.462-31.76c-2.938-13.084-4.081-31.884-4.938-65.525c-0.432-10.174,0.067-26.568-2.295-26.568c-2.461,0-2.279,19.271-2.284,26.611c-1.59,33.611-1.987,52.232-5.112,65.627c0.227,5.25,1.747,25.016,1.553,31.709c-1.801,20.293-3.993,39.382-5.702,65.643c1.141,4.023,2.657,6.222,2.391,11.705c-2.076,21.102-11.302,18.452-13.633,18.416c-18.887,0.036-5.296-14.152-4.067-18.422c1.872-4.363,1.288-2.363,2.164-11.701c0.344-14.65,0.517-16.014-0.278-24.195c-1.752-13.08-2.629-18.169-5.729-41.432c-0.634-9.539-0.78-10.629,0.488-29.4c1.089-15.717,0.669-4.945,0.676-15.749c-1.562-23.451-2.133-25.104-7.648-52.216c-3.298-24.964-3.378-20.697-4.639-37.996c0.655-15.453,0.553-16.708,2.08-33.086c2.536-13.362,2.821-13.236,5.041-18.924c1.992-5.731,2.773-6.61,3.278-15.24c-0.123-14.71-1.355-13.581-4.216-31.948c-0.343-4.345-1.045-12.384-1.842-12.442c-1.656,0-3.951,19.881-4.265,21.559c-0.911,7.563-0.697,7.122-3.025,26.396c-9.122,46.979-13.383,60.781-13.798,62.16c2.674,10.214-1.387,22.694-2.508,24.767c11.765,21.758-3.755,11.437-5.124,10.295c-12.581-9.029-6.581-22.137-1.618-35.061c0.565-46.464,1.617-41.065,4.425-65.677c2.358-15.631,3.697-22.884,3.913-26.429c4.08-25.997,3.838-44.722,14.236-48.261c18.611-5.66,24.028-5.824,29.7-10.535c2.224-1.86,3.368-11.043,3.217-14.345c-1.009-1.847-3.047-10.829-3.736-12.644c-0.201,0.438-2.053,1.134-3.827-6.01c-0.306-1.248-2.382-7.466,0.618-6.479c-0.6-1.662-3.181-5.926-1.205-14.726C82.233,35.208,85.065,24.025,102.392,24.025z 
    mask_x: 181
    mask_y: 0
    rect_x: 32
    rect_y: 52.5
    rect_height: 400
    rect_width: 300
    marker_json:
    default_marker_json:
    default_marker_svg:  
    default_user: true
    