dashboard_banner:
  1:
    image: uploads/ltf/products/banner/1.png
    caption: Black and White
    price: 40
    index: 1
    type: stylist_recommendations
    id: 0
    product_ids: [572,605,571,606,569]
    group_ids:
      bottom: 572
      top: 605
      dress: 571
    disable: false
  2:
    image: uploads/ltf/products/banner/2.png
    caption: Light and Casual
    price: 40
    index: 2
    type: stylist_recommendations
    product_ids: [716,577,570,594,604,584]
    group_ids:
      bottom: 716
      top: 604
      top: 570
    id: 0
    disable: false
  3:
    image: uploads/ltf/products/banner/3.png
    caption: Beyond the Blues
    price: 40
    index: 3
    type: stylist_recommendations
    product_ids: [588,580,604,566,592,570,591]
    group_ids:
      bottom: 588
      top: 580
    id: 0
    disable: false
  4:
    image: uploads/ltf/products/banner/4.png
    caption: Business Casual 
    price: 40
    index: 4
    type: stylist_recommendations
    product_ids: [593,573,602,581]
    group_ids:
      bottom: 593
      dress: 573
      dress: 602
    id: 0
    disable: false
  5:
    image: uploads/ltf/products/banner/5.png
    caption: Contemporary
    price: 40
    index: 5
    type: stylist_recommendations
    product_ids: [565,569,604,592,605,571]
    group_ids:
      bottom: 565
      top: 569
    id: 0
    disable: false
  6:
    image: uploads/ltf/products/banner/6.png
    caption: Modern Edge
    price: 40
    index: 6
    type: stylist_recommendations
    product_ids: [564, 581, 578, 580]
    group_ids:
      bottom: 564
      dress: 581
      dress: 578
    id: 0
    disable: false
    
    
    