dashboard_banner:
  1:
    image: /uploads/ltf/products/banner/recommendation_image@2x.png
    caption: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    price: 10
    index: 1
    link:
      brand_id: 63
      retailer_id: 23
    disable: false
  2:
    image: /uploads/ltf/products/banner/recommendation_image_2@2x.png
    caption: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    price: 20
    index: 2
    link:
      brand_id: 54
      retailer_id: 17
    disable: false
  3:
    image: /uploads/ltf/products/banner/recommendation_image_-3@2x.png
    caption: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    price: 30
    index: 3
    link:
      brand_id: 52
      retailer_id: 16
    disable: false
  4:
    image: /uploads/ltf/products/banner/recommendation_image_4@2x.png
    caption: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    price: 40
    index: 3
    link:
      brand_id: 48
      retailer_id: 20
    disable: false
