category_banner:
  banner_type: 2
  display_screen: shop
  sorting: 10
  type: banner
  object: 
    0:
      id: 9
      shoplook_id: null
      product_id: null
      title: Denim
      banner_image: http://dev.selfiestyler.com/uploads/ltf/banner/iphone/5877631388064.png
      image_position: right
      banner_type: 2
      description: Hey we're adding plus sizes soon
      sorting: 3
      price_min: null
      price_max: null
      type: banner
   