#----------------------------- User Routes--------------------------------------#
ws_login:
    pattern:  /web_service/login
    defaults: { _controller: LoveThatFitWebServiceBundle:User:login }
  
ws_registration_create:
   pattern:  /web_service/register
   defaults: { _controller: LoveThatFitWebServiceBundle:User:registrationCreate}

ws_measurement_edit:
   pattern:  /web_service/measurement_edit
   defaults: { _controller: LoveThatFitWebServiceBundle:User:measurementEdit}
 
ws_change_password:
   pattern:  /web_service/change_password
   defaults: { _controller: LoveThatFitWebServiceBundle:User:changePassword}
  
ws_forget_password:
    pattern:  /web_service/forget_password
    defaults: { _controller: LoveThatFitWebServiceBundle:User:forgetPassword }
   
   
ws_edit_profile:
   pattern:  /web_service/edit_profile
   defaults: { _controller: LoveThatFitWebServiceBundle:User:editProfile}   
    
ws_user_profile:
   pattern:  /web_service/user_profile
   defaults: { _controller: LoveThatFitWebServiceBundle:User:userProfile}    
   
ws_iphone_shoulder_outseam:
   pattern:  /web_service/iphone_shoulder_outseam
   defaults: { _controller: LoveThatFitWebServiceBundle:User:shoulderOutseamEdit}   

ws_image_upload:
   pattern:  /web_service/image_upload
   defaults: { _controller: LoveThatFitWebServiceBundle:User:imageUpload}


ws_check_token__forget_password:
    pattern:  /web_service/check_token_forget_password
    defaults: { _controller: LoveThatFitWebServiceBundle:User:checkTokenforgetPassword }
    

ws_update__forget_password:
    pattern:  /web_service/check_update_password
    defaults: { _controller: LoveThatFitWebServiceBundle:User:updateForgetPassword }  

checkEmail:
   pattern:  /web_service/checkemail
   defaults: { _controller: LoveThatFitWebServiceBundle:User:emailCheck}   
   
avatarUpload:
   pattern:  /web_service/upload_avatar
   defaults: { _controller: LoveThatFitWebServiceBundle:User:avatarUpload} 
   
constantValue:
   pattern:  /web_service/constant_values
   defaults: { _controller: LoveThatFitWebServiceBundle:User:ConstantValues}
   
registrationSizechart:
   pattern:  /web_service/registration_sizechart
   defaults: { _controller: LoveThatFitWebServiceBundle:User:sizeChartForReg}

   
   

#----------------------------- Product Routes----------------------------------#    
ws_brands:
    pattern:  /web_service/brands
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:brandList,_format: json}
    
ws_new_products:
    pattern:  /web_service/newproducts
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:newproductListing,_format: json  }    

ws_new_products_detail:
    pattern:  /web_service/newproducts_detail
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:newproductDetail,_format: json  }    


ws_products:
    pattern:  /web_service/products
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:productList,_format: json  }

ws_clothingtype_brand:
    pattern:  /web_service/clothingtype_brands
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:byBrandClothingType,_format: json}

ws_product_detail:
    pattern:  /web_service/product_detail
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:productDetail,_format: json}

ws_brand_list_size_chart:
   pattern:  /web_service/brand_list_size_chart
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:brandListSizeChart}

ws_size_chart:
   pattern:  /web_service/size_chart
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:sizeCharts}
   
ws_default_fittng_alert:
   pattern:  /web_service/default_fitting_alerts
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:defaultProductFittingAlert}
   
ws_fittng_alert:
   pattern:  /web_service/fitting_alerts
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:getFeedBackJSON}

ws_love_item:
   pattern:  /web_service/love_item
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:loveItem}
   
ws_try_history:
   pattern:  /web_service/user_try_history
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:userTryHistory} 

userFavouriteList:
   pattern:  /web_service/user_favourite_list
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:favouriteByUser}
 
ws_images_ul:
   pattern:  /web_service/images_url
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:imagesUrl}   
   
ws_product_syn:
   pattern:  /web_service/product_sync
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:getProductSyn}   
   
ws_brand_syn:
   pattern:  /web_service/brand_sync
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:getBrandSync}   
   
ws_product_detail_syn:
   pattern:  /web_service/product_detail_sync
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:getProductDetailSyn} 

ws_send_push_notifcation:
   pattern:  /web_service/send_push_notification
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:sendPushNotifcation}  

ws_get_notification_type:
   pattern:  /web_service/get_notification_type
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:getNotificationType}  

   
   

 


test_product:
   pattern:  /web_service/product_specification
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:test_product_specification}
   
service_interface:
   pattern:  /web_service/service_interface
   defaults: { _controller: LoveThatFitWebServiceBundle:Default:serviceInterface}


  
