web_service_create:
    pattern:  /web_service/create
    defaults: { _controller: LoveThatFitWebServiceBundle:User:createForm }


web_service_login:
    pattern:  /web_service/login
    defaults: { _controller: LoveThatFitWebServiceBundle:User:login }
    
    
web_service_brands:
    pattern:  /web_service/brands
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:brandList,_format: json}

web_service_clothingtype:
    pattern:  /web_service/clothingtype/{page_number}/{sort}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:clothingTypeList,_format: json  ,page_number: 1, sort:id }

web_service_products:
    pattern:  /web_service/products
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:productList,_format: json  }

web_service_products_by_brand:
    pattern:  /web_service/products_by_brand/{brand_id}/{gender}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:productListByBrand,_format: json,brand_id:1,gender:'M'  }

web_service_clothingtype_brand:
    pattern:  /web_service/clothingtype_brands
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:byBrandClothingType,_format: json}

web_service_products_by_brand_type:
    pattern:  /web_service/products_by_brand_type/{brand_id}/{clothing_type_id}/{gender}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:productListByBrandClothingType,_format: json,brand_id:1,clothing_type_id:1,gender:'M'}
  
web_service_product_detail:
    pattern:  /web_service/product_detail
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:productDetail,_format: json}

web_service_my_closet:
    pattern:  /web_service/my_closet/{user_id}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:myClostList,_format: json,user_id:1}

web_service_registration_create:
   pattern:  /web_service/register
   defaults: { _controller: LoveThatFitWebServiceBundle:User:registrationCreate}
   
web_service_measurement_edit:
   pattern:  /web_service/measurement_edit
   defaults: { _controller: LoveThatFitWebServiceBundle:User:measurementEdit}
   
web_service_change_password_form:
   pattern:  /web_service/change_password_form
   defaults: { _controller: LoveThatFitWebServiceBundle:User:changePasswordForm}

web_service_change_password:
   pattern:  /web_service/change_password
   defaults: { _controller: LoveThatFitWebServiceBundle:User:changePassword}
   
web_service_edit_profile:
   pattern:  /web_service/edit_profile
   defaults: { _controller: LoveThatFitWebServiceBundle:User:editProfile}
web_service_user_profile:
   pattern:  /web_service/user_profile
   defaults: { _controller: LoveThatFitWebServiceBundle:User:userProfile}

web_service_iphone_shoulder_outseam:
   pattern:  /web_service/iphone_shoulder_outseam
   defaults: { _controller: LoveThatFitWebServiceBundle:User:shoulder_outseamEdit}

web_service_image_upload:
   pattern:  /web_service/image_upload
   defaults: { _controller: LoveThatFitWebServiceBundle:User:imageUpload}
   
   
web_service_brand_list_size_chart:
   pattern:  /web_service/brand_list_size_chart
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:brandListSizeChart}

web_service_size_chart:
   pattern:  /web_service/size_chart
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:sizeCharts}

web_service_form:
   pattern:  /web_service/form
   defaults: { _controller: LoveThatFitWebServiceBundle:User:imageForm}


   
   
   



  
