ws_create:
    pattern:  /web_service/create
    defaults: { _controller: LoveThatFitWebServiceBundle:User:createForm }


ws_login:
    pattern:  /web_service/login
    defaults: { _controller: LoveThatFitWebServiceBundle:User:login }
    
    
ws_brands:
    pattern:  /web_service/brands
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:brandList,_format: json}

ws_products:
    pattern:  /web_service/products
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:productList,_format: json  }

ws_clothingtype_brand:
    pattern:  /web_service/clothingtype_brands
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:byBrandClothingType,_format: json}

ws_product_detail:
    pattern:  /web_service/product_detail
    defaults: { _controller: LoveThatFitWebServiceBundle:Product:productDetail,_format: json}

web_service_my_closet:
    pattern:  /web_service/my_closet/{user_id}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:myClostList,_format: json,user_id:1}

ws_registration_create:
   pattern:  /web_service/register
   defaults: { _controller: LoveThatFitWebServiceBundle:User:registrationCreate}
   
ws_measurement_edit:
   pattern:  /web_service/measurement_edit
   defaults: { _controller: LoveThatFitWebServiceBundle:User:measurementEdit}
   
ws_change_password_form:
   pattern:  /web_service/change_password_form
   defaults: { _controller: LoveThatFitWebServiceBundle:User:changePasswordForm}

ws_change_password:
   pattern:  /web_service/change_password
   defaults: { _controller: LoveThatFitWebServiceBundle:User:changePassword}
   
ws_edit_profile:
   pattern:  /web_service/edit_profile
   defaults: { _controller: LoveThatFitWebServiceBundle:User:editProfile}
ws_user_profile:
   pattern:  /web_service/user_profile
   defaults: { _controller: LoveThatFitWebServiceBundle:User:userProfile}

ws_iphone_shoulder_outseam:
   pattern:  /web_service/iphone_shoulder_outseam
   defaults: { _controller: LoveThatFitWebServiceBundle:User:shoulder_outseamEdit}

ws_image_upload:
   pattern:  /web_service/image_upload
   defaults: { _controller: LoveThatFitWebServiceBundle:User:imageUpload}
   
ws_brand_list_size_chart:
   pattern:  /web_service/brand_list_size_chart
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:brandListSizeChart}

ws_size_chart:
   pattern:  /web_service/size_chart
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:sizeCharts}

ws_default_fittng_alert:
   pattern:  /web_service/default_fitting_alerts
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:defaultProductFittingAlert}
ws_fittng_alert:
   pattern:  /web_service/fitting_alerts
   defaults: { _controller: LoveThatFitWebServiceBundle:Product:getFeedBackJSON}



  
