web_service_create:
    pattern:  /web_service/create
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:createForm }


web_service_login:
    pattern:  /web_service/login
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:login }
    
    
web_service_brands:
    pattern:  /web_service/brands/{page_number}/{sort}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:brandList,_format: json  ,page_number: 1, sort:id }

web_service_clothingtype:
    pattern:  /web_service/clothingtype/{page_number}/{sort}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:clothingTypeList,_format: json  ,page_number: 1, sort:id }

web_service_products:
    pattern:  /web_service/products
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:productList,_format: json  }

web_service_products_by_brand:
    pattern:  /web_service/products_by_brand/{brand_id}/{gender}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:productListByBrand,_format: json,brand_id:1,gender:'M'  }

web_service_products_by_type:
    pattern:  /web_service/products_by_type/{clothing_type_id}/{gender}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:productListByClothingType,_format: json,clothing_type_id:1,gender:'M'}

web_service_products_by_brand_type:
    pattern:  /web_service/products_by_brand_type/{brand_id}/{clothing_type_id}/{gender}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:productListByBrandClothingType,_format: json,brand_id:1,clothing_type_id:1,gender:'M'}
  

web_service_product_detail:
    pattern:  /web_service/products_detail/{product_id}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:productDetailList,_format: json,product_id:1}

web_service_my_closet:
    pattern:  /web_service/my_closet/{user_id}
    defaults: { _controller: LoveThatFitWebServiceBundle:Default:myClostList,_format: json,user_id:1}

web_service_createform:
    pattern:  /web_service/registration_form
    defaults: { _controller: LoveThatFitWebServiceBundle:User:createRegistrationForm }

web_service_registration_create:
   pattern:  /web_service/registration_create
   defaults: { _controller: LoveThatFitWebServiceBundle:User:registrationCreate}
