
brands:
    pattern:  /web_service/brands
    request_type: get
    #

brand_list_size_chart:
   pattern:  /web_service/brand_list_size_chart
   request_type: get


clothingtype_brand:
    pattern:  /web_service/clothingtype_brands
    request_type: get
    #

constantValue:
   pattern:  /web_service/constant_values
   request_type: get
   #
#-----------------------------------------
brand_retailer:
    pattern:  /web_service/brand_retailer
    params:
      date: 1388577600
    request_type: post
    #*date


#-------------------- User Login & registration & profile ---------------------------
login:
    pattern:  /web_service_test/login
    params:
      email:  example@ltf.com
      password: ltf123
      deviceType: iphone5
    request_type: post
    description: login & wuthenticate user & returns user details
    # array('email'=>'','password'=>'Apple2013','deviceType'=>'');
#-------------------- User Login & registration & profile ---------------------------
user_detail:
    pattern:  /web_service/user_detail
    params:
      authTokenWebService:  'de81d026177b7300c97976a5d1459b2d'      
    request_type: post
    description: login & wuthenticate user & returns user details    
     
registration_create:
   pattern:  /web_service_test/register
   params:
     email:  example@ltf.com
     password: ltf123
     gender: f
     zipcode: 123456
     weight: 80.00
     height: 61.00
     bust: 0.00
     neck: 0.00
     chest: 0.00
     inseam: 0.00
     hip: 0.00
     waist: 0.00
     deviceType: ipad
     bodyShape: pear
     braSize: 30 b
     bodyType: Regular
     deviceId: tempID
     sleeve: 0.00
     targetTop: Banana Republic
     targetBottom: CARMEN MARC VALVO
     targetDress: CARMEN MARC VALVO
     topSize: 0
     bottomSize: 0
     dressSize: 4
   request_type: post
   #{"email":"kamran@hotmail.com","password":"123456","gender":"f","zipcode":"123456","weight":"80.00","height":"61.00","bust":"0.00","neck":"0.00","chest":"0.00","inseam":"0.00","hip":"0.00","waist":"0.00","deviceType":"ipad","bodyShape":"pear","braSize":"30 b","bodyType":"Regular","deviceId":"tempID","sleeve":"0.00","targetTop":"Banana Republic","targetBottom":"CARMEN MARC VALVO","targetDress":"CARMEN MARC VALVO","topSize":"0","bottomSize":"0","dressSize":"4"}

edit_profile:
   pattern:  /web_service_test/edit_profile
   params:
     email: oldnavywomen0@ltf.com
     firstName: test
     password: 123456
     gender: f
     zipcode: 123
     sc_top_id: 2
     sc_bottom_id: 2
     sc_dress_id: 2
     weight: 4
     neck: 4
     bust: 5
   request_type: post
   # $decoded=array('email'=>'oldnavywomen0@ltf.com','firstName'=>'test','password'=>'123456','gender'=>'f','zipcode'=>'123','sc_top_id'=>'2','sc_bottom_id'=>'2','sc_dress_id'=>'2','weight'=>4,'neck'=>4,'bust'=>5);

measurement_edit:
   pattern:  /web_service_test/measurement_edit
   params:
     email: kamran@hotmail.com
     authTokenWebService: 97fc8d115394f3f1947f315783e29e0e
     deviceType: 4s
     heightPerInch: 6
     weight: 100
     thigh: 10
   request_type: post
   #array('email'=>'kamran@hotmail.com','authTokenWebService'=>'97fc8d115394f3f1947f315783e29e0e','deviceType'=>'4s','heightPerInch'=>'6','weight'=>'100','thigh'=>10);

user_profile:   
   pattern:  /web_service_test/user_profile
   params:
     email: abc@ltf.com
     type:  type
   request_type: post
   description: gets email & return user details

avatarUpload:
   pattern:  /web_service_test/upload_avatar
   params:
     email: iphone@gmail.com
     file: need file
   request_type: post
   #email,file
   
image_upload:
   pattern:  /web_service_test/image_upload
   params:
     email: iphone@gmail.com
     deviceType: 4s
     heightPerInch: 6
     file: need file
   request_type: post
   # email,deviceType,heightPerInch,file;    

iphone_shoulder_outseam:
   pattern:  /web_service_test/iphone_shoulder_outseam
   params:
     email: iphone@gmail.com
     authTokenWebService: 121c421783cd4d71d871ec16a1296091
     deviceType: 4s
     heightPerInch: 6
   request_type: post
   #$request_array=array('email'=>'iphone@gmail.com','authTokenWebService'=>'121c421783cd4d71d871ec16a1296091','deviceType'=>'4s','heightPerInch'=>'6');

change_password:
   pattern:  /web_service_test/change_password
   params:
     email: kamran@hotmail.com
     authTokenWebService: 97fc8d115394f3f1947f315783e29e0e
     password: 12345
     old_password: 67890
   request_type: post
   #aray('authTokenWebService',email='oldnavywomen0@ltf.com';password='12';old_password='123456';)

forget_password:
    pattern:  /web_service_test/forget_password
    params:
      email: kamran@hotmail.com
    request_type: post
  # array(email)  

check_token__forget_password:
    pattern:  /web_service_test/check_token_forget_password
    params:
      email: iphone@gmail.com
      authTokenWebService: 121c421783cd4d71d871ec16a1296091
    request_type: post
    #email,auth_token

update__forget_password:
    pattern:  /web_service_test/check_update_password
    params:
      email: iphone@gmail.com
      password: 12345
    request_type: post      
    #email,password

checkEmail:
   pattern:  /web_service_test/checkemail
   params:
     email: iphone@gmail.com
   request_type: post     
   #email

#----------------------------- user & product -------------------------------

love_item:
   pattern:  /web_service_test/love_item
   params:
     authTokenWebService: 121c421783cd4d71d871ec16a1296091
     productItemId: 12
     user_id: 13
     like: like
   request_type: post
   #array('authTokenWebService'=>'121c421783cd4d71d871ec16a1296091','productItemId'=>12,'userId'=>17,'like'=>'like');

try_history:
   pattern:  /web_service_test/user_try_history
   params:
     authTokenWebService: 121c421783cd4d71d871ec16a1296091
     user_id: 13
   request_type: post
   #authTokenWebService,user_id

userFavouriteList:
   pattern:  /web_service_test/user_favourite_list
   params:
     authTokenWebService: 121c421783cd4d71d871ec16a1296091
     user_id: 13
   request_type: post
  #authTokenWebService,user_id
  
default_fittng_alert:
   pattern:  /web_service_test/default_fitting_alerts
   params:
     authTokenWebService: 121c421783cd4d71d871ec16a1296091
     product_id: 11
     user_id: 13
   request_type: post
   #array('authTokenWebService'=>'123','productId'=>11,'userId'=>17);
product_syn:
   pattern:  /web_service_test/product_sync
   params:
     authTokenWebService: 121c421783cd4d71d871ec16a1296091
     date: 1388577600
   request_type: post
   #array('authTokenWebService'=>'567a31256454a1dd8157eba6ddfc5447','date'=>'1388577600');

brand_syn:
   pattern:  /web_service_test/brand_sync
   params:
     authTokenWebService: 121c421783cd4d71d871ec16a1296091
     date: 1388577600
   request_type: post
   #array('authTokenWebService'=>'567a31256454a1dd8157eba6ddfc5447','date'=>'1388577600');
   
product_detail_syn:
   pattern:  /web_service_test/product_detail_sync
   params:
     authTokenWebService: 121c421783cd4d71d871ec16a1296091
     date: 1388577600
   request_type: post
  #array('authTokenWebService'=>'567a31256454a1dd8157eba6ddfc5447','date'=>'1388577600');

#----------------------------------------------------
new_products:
    pattern:  /web_service_test/newproducts
    params:
      authTokenWebService: 121c421783cd4d71d871ec16a1296091
    request_type: post
    #authTokenWebService

new_products_detail:
    pattern:  /web_service_test/newproducts_detail
    params:
      authTokenWebService: 121c421783cd4d71d871ec16a1296091
    request_type: post
    #authTokenWebService

products:
    pattern:  /web_service_test/products
    params:
      authTokenWebService: 121c421783cd4d71d871ec16a1296091
      brand_id: 5
      type: brand
    request_type: post
    #array('authTokenWebService'=>'46ed5a3aa2f09ba0436612289b93aee5','brandId'=>5,'type'=>'brand');

product_detail:
    pattern:  /web_service_test/product_detail
    params:
      authTokenWebService: 121c421783cd4d71d871ec16a1296091
      id: 123
      user_id: 34
    request_type: post
    #authTokenWebService,'id'=>186,'user_id'=>1
    
#------------------------------------------------------------


size_chart:
   pattern:  /web_service_test/size_chart
   params:
     gender: f
     body_type: Petite
     target_top: 1
     top_size: 1
     target_bottom: 2
     bottom_size: 2
     target_dress: 3
     dress_size: 3
   request_type: post
   #('gender'=>'f','body_type'=>'Petite','target_top'=>1,'top_size'=>1,'target_bottom'=>2,'bottom_size'=>2,'target_dress'=>3,'dress_size'=>3);

registrationSizechart:
   pattern:  /web_service_test/registration_sizechart
   request_type: get
   
images_ul:
   pattern:  /web_service_test/images_url

product_for_user_syn:
   pattern:  /web_service_test/product_user_sync
   request_type: get
