device_config:
    
  iphone5:
    svg_mask_x: 55
    svg_mask_y: 55
    pixel_per_inch: 6.891
    jt_pixel_added: 0.483
    ground_marker_px: 0
    max_user_height_inch: 65
    svg_scale_ratio: 0
    device_model: iphone5
    product_px_per_inch: 17
    neck_exlusion_px: 238
    screen_available_height_px: 0
    total_screen_height_px: 568
    resize_ratio_jt: 1
  
  iphone5c:
    svg_mask_x: 55
    svg_mask_y: 55
    pixel_per_inch: 6.891
    jt_pixel_added: 0.483
    ground_marker_px: 0
    max_user_height_inch: 74
    svg_scale_ratio: 0
    device_model: iphone5c
    product_px_per_inch: 17
    neck_exlusion_px: 238
    screen_available_height_px: 0
    total_screen_height_px: 568
    resize_ratio_jt: 1.052199389069704
    
  iphone5s:
    pixel_per_inch: 6.891
    max_user_height_inch: 74
    device_model: iphone6
    product_px_per_inch: 17
    total_screen_height_px: 568
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 55
    svg_mask_y: 55
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1.052199389069704
    
  iphoneSE:
    pixel_per_inch: 6.891
    max_user_height_inch: 74
    device_model: iphone6
    product_px_per_inch: 17
    total_screen_height_px: 568
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 55
    svg_mask_y: 55
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1.052199389069704
    
  iphone6:
    pixel_per_inch: 8.424
    max_user_height_inch: 74
    device_model: iphone6
    product_px_per_inch: 17
    total_screen_height_px: 667
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
    
  iphone6s:
    pixel_per_inch: 8.424
    max_user_height_inch: 74
    device_model: iphone6s
    product_px_per_inch: 17
    total_screen_height_px: 667
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
    
  iphone6plus:
    pixel_per_inch: 9.295
    max_user_height_inch: 74
    device_model: iphone6plus
    product_px_per_inch: 17
    total_screen_height_px: 736
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  iphone6splus:
    pixel_per_inch: 9.295
    max_user_height_inch: 74
    device_model: iphone6splus
    product_px_per_inch: 17
    total_screen_height_px: 736
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  iphone7:
    pixel_per_inch: 8.424
    max_user_height_inch: 74
    device_model: iphone7
    product_px_per_inch: 17
    total_screen_height_px: 667
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  iphone7plus:
    pixel_per_inch: 9.295
    max_user_height_inch: 74
    device_model: iphone7plus
    product_px_per_inch: 17
    total_screen_height_px: 736
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1