parameters:
#    love_that_fit_admin.example.class: LoveThatFit\AdminBundle\Example

services:
#    love_that_fit_admin.example:
#        class: %love_that_fit_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
constants:
  device_bootstrap:
    resolution_scale:    
      pixcel_per_inch: 16
      inches: 72
      standard: 1152
      iphone4s: 690
      iphone5:  840
      ipad:  1024
      ipad_retina:  2048
      
  pagination:
    limit: 30
    default_page: first
  
  gender:
    men: m 
    women: f
  
  target: 
     ({top, bottom, dress})
  
  body_types:
     ({regular, petite, tall})
  
  size_titles:
     ({xxs, xs, s, m, l, xl, xxl})
  
  size_numbers:
     ({00, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20})
  
  size_charts:
    xxs: 00
    xs: 0
    xs: 2
    s: 4
    s: 6
    m: 8
    m: 10
    l: 12
    l: 14
    xl: 18
    xl: 18
    xxl: 20
  
Twitter:  
consumer_key: 9GBx1IchmgsTC404I52w
consumer_secret: HC6fR9dZYl8zqzHNx36eCvlWvJ0HCmPzMJr3Pqj88
oauth_access_token : 1667582922-O5JzsoBc7fmfUR2jYVHrnCWsIiOWDDO38uXwpQk
oauth_access_token_secret: sa0TN4vVjQtU82o09VatP68oLISZjkXd3erZnGk
screen_name: LoveThatFit



    