parameters:
#    love_that_fit_admin.example.class: LoveThatFit\AdminBundle\Example

services:
#    love_that_fit_admin.example:
#        class: %love_that_fit_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
constants:
  device_bootstrap:
    resolution_scale:    
      web: 
        pixel_per_inch: 6
        pixel_height : 1152
        inch_height: 72
      iphone4s: 
        pixel_per_inch: 14
        pixel_height : 696
      iphone5:  
        pixel_per_inch: 17
        pixel_height : 870
      ipad:
        pixel_per_inch: 18.125
        pixel_height : 870
      ipad_retina:
        pixel_per_inch: 18.125
        pixel_height : 870
      
  pagination:
    limit: 30
    default_page: first
  
  gender:
    men: m 
    women: f
  
  target: 
     top: top
     bottom: bottom
     dress: dress
     
  body_types:
     ({regular, petite, tall})
 
  body_types_search:
      regular: regular
      petite: petite
      tall: tall
  
  size_titles:
     ({xxs, xs, s, m, l, xl, xxl})
  
  size_numbers:
     ({0, 1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20})
  
  size_charts:
    xxs: 0
    xs: 1
    xs: 2
    s: 4
    s: 6
    m: 8
    m: 10
    l: 12
    l: 14
    xl: 16
    xl: 18
    xxl: 20
    xxl: 22
    xxl: 24
    xxl: 26
    xxl: 28
  
Twitter:  
consumer_key: 9GBx1IchmgsTC404I52w
consumer_secret: HC6fR9dZYl8zqzHNx36eCvlWvJ0HCmPzMJr3Pqj88
oauth_access_token : 1667582922-O5JzsoBc7fmfUR2jYVHrnCWsIiOWDDO38uXwpQk
oauth_access_token_secret: sa0TN4vVjQtU82o09VatP68oLISZjkXd3erZnGk
screen_name: LoveThatFit



    