device_config:
  
  iphone4:
    pixel_per_inch: 6.062
    max_user_height_inch: 74
    device_model: iphone4
    product_px_per_inch: 17
    total_screen_height_px: 480
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
  
  iphone4s:
    pixel_per_inch: 6.062
    max_user_height_inch: 74
    device_model: iphone4s
    product_px_per_inch: 17
    total_screen_height_px: 480
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
    
  iphone5:
    pixel_per_inch: 7.173
    max_user_height_inch: 74
    device_model: iphone5
    product_px_per_inch: 17
    total_screen_height_px: 568
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
  
  iphone5c:
    pixel_per_inch: 7.173
    max_user_height_inch: 74
    device_model: iphone5c
    product_px_per_inch: 17
    total_screen_height_px: 568
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
    
  iphone5s:
    pixel_per_inch: 7.173
    max_user_height_inch: 74
    device_model: iphone5s
    product_px_per_inch: 17
    total_screen_height_px: 568
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
    
  iphoneSE:
    pixel_per_inch: 7.173
    max_user_height_inch: 74
    device_model: iphoneSE
    product_px_per_inch: 17
    total_screen_height_px: 568
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
    
  iphone6:
    pixel_per_inch: 8.424
    max_user_height_inch: 74
    device_model: iphone6
    product_px_per_inch: 17
    total_screen_height_px: 667
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
    
  iphone6s:
    pixel_per_inch: 8.424
    max_user_height_inch: 74
    device_model: iphone6s
    product_px_per_inch: 17
    total_screen_height_px: 667
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
    
  iphone6plus:
    pixel_per_inch: 9.295
    max_user_height_inch: 74
    device_model: iphone6plus
    product_px_per_inch: 17
    total_screen_height_px: 736
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  iphone6splus:
    pixel_per_inch: 9.295
    max_user_height_inch: 74
    device_model: iphone6splus
    product_px_per_inch: 17
    total_screen_height_px: 736
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  iphone7:
    pixel_per_inch: 8.424
    max_user_height_inch: 74
    device_model: iphone7
    product_px_per_inch: 17
    total_screen_height_px: 667
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  iphone7plus:
    pixel_per_inch: 9.295
    max_user_height_inch: 74
    device_model: iphone7plus
    product_px_per_inch: 17
    total_screen_height_px: 736
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  iphonex:
    pixel_per_inch: 10.255
    max_user_height_inch: 74
    device_model: iphonex
    product_px_per_inch: 17
    total_screen_height_px: 812
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  simulator:
    pixel_per_inch: 8.424
    max_user_height_inch: 74
    device_model: simulator
    product_px_per_inch: 17
    total_screen_height_px: 667
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  ipad:
    pixel_per_inch: 6.062
    max_user_height_inch: 74
    device_model: ipad
    product_px_per_inch: 17
    total_screen_height_px: 480
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  iphone8:
    pixel_per_inch: 8.424
    max_user_height_inch: 74
    device_model: iphone8
    product_px_per_inch: 17
    total_screen_height_px: 667
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1

  iphone8plus:
    pixel_per_inch: 9.295
    max_user_height_inch: 74
    device_model: iphone8plus
    product_px_per_inch: 17
    total_screen_height_px: 736
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 795
    actual_bottom_prod_empty_area: 1958
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1