device_config:
    
  iphone5:
    svg_mask_x: 55
    svg_mask_y: 55
    pixel_per_inch: 6.891
    jt_pixel_added: 0.483
    ground_marker_px: 0
    max_user_height_inch: 65
    svg_scale_ratio: 0
    device_model: iphone5
    product_px_per_inch: 17
    neck_exlusion_px: 238
    screen_available_height_px: 0
    total_screen_height_px: 568
    resize_ratio_jt: 1
  
  iphone5c:
    svg_mask_x: 55
    svg_mask_y: 55
    pixel_per_inch: 6.891
    jt_pixel_added: 0.483
    ground_marker_px: 0
    max_user_height_inch: 74
    svg_scale_ratio: 0
    device_model: iphone5c
    product_px_per_inch: 17
    neck_exlusion_px: 238
    screen_available_height_px: 0
    total_screen_height_px: 568
    resize_ratio_jt: 1.052199389069704
    
  iphone5s:
    svg_mask_x: 55
    svg_mask_y: 55
    pixel_per_inch: 6.891
    jt_pixel_added: 0.483
    ground_marker_px:
    max_user_height_inch: 74
    svg_scale_ratio: 0
    device_model: iphone5s
    product_px_per_inch: 17
    neck_exlusion_px: 238
    screen_available_height_px: 0
    total_screen_height_px: 568
    resize_ratio_jt: 1.052199389069704
    
  iphone6:
    pixel_per_inch: 9.21
    max_user_height_inch: 74
    device_model: iphone6
    product_px_per_inch: 17
    total_screen_height_px: 667
    actual_product_img_ppi: 60
    actual_top_prod_empty_area: 840
    actual_bottom_prod_empty_area: 760
    svg_mask_x: 66
    svg_mask_y: 66
    jt_pixel_added: 0
    ground_marker_px: 0
    svg_scale_ratio: 0
    product_px_per_inch: 17
    neck_exlusion_px: 0
    screen_available_height_px: 0
    resize_ratio_jt: 1
    
  iphone6s:
    svg_mask_x: 66
    svg_mask_y: 66
    pixel_per_inch: 7.797
    jt_pixel_added: 0.483 
    ground_marker_px: 0
    max_user_height_inch: 73
    svg_scale_ratio: 0
    device_model: iphone6s
    product_px_per_inch: 17
    neck_exlusion_px: 238
    screen_available_height_px: 0
    total_screen_height_px: 667
    resize_ratio_jt: 1.131335
    
  iphoneSE:
    svg_mask_x: 66
    svg_mask_y: 66
    pixel_per_inch: 7.797
    jt_pixel_added: 0.483 
    ground_marker_px: 0
    max_user_height_inch: 73
    svg_scale_ratio: 0
    device_model: iphoneSE
    product_px_per_inch: 17
    neck_exlusion_px: 238
    screen_available_height_px: 0    
    total_screen_height_px: 667
    resize_ratio_jt: 1

  iphone6plus:
    svg_mask_x: 66
    svg_mask_y: 66
    pixel_per_inch: 7.797
    jt_pixel_added: 0.483
    ground_marker_px: 0
    max_user_height_inch: 73
    svg_scale_ratio: 0
    device_model: iphone6s
    product_px_per_inch: 17
    neck_exlusion_px: 238
    screen_available_height_px: 0
    total_screen_height_px: 667
    resize_ratio_jt: 1.131335

  iphone7:
    svg_mask_x: 66
    svg_mask_y: 66
    pixel_per_inch: 7.797
    jt_pixel_added: 0.483
    ground_marker_px: 0
    max_user_height_inch: 73
    svg_scale_ratio: 0
    device_model: iphone6s
    product_px_per_inch: 17
    neck_exlusion_px: 238
    screen_available_height_px: 0
    total_screen_height_px: 667
    resize_ratio_jt: 1.131335

  iphone7plus:
    svg_mask_x: 66
    svg_mask_y: 66
    pixel_per_inch: 7.797
    jt_pixel_added: 0.483
    ground_marker_px: 0
    max_user_height_inch: 73
    svg_scale_ratio: 0
    device_model: iphone6s
    product_px_per_inch: 17
    neck_exlusion_px: 238
    screen_available_height_px: 0
    total_screen_height_px: 667
    resize_ratio_jt: 1.131335