sizes:
  "00":
    neck: 12
    bust: 34.25
    waist: 24
    hips: 33.75
    shoulder_across_back: 13.25
    thigh: 18
    knee: 13
    calf: 12.5
    ankle: 7.25
    tricep: 8
    bicep: 7.5
    wrist: 5.5
    arm: 22
  0:
    neck: 12.5
    bust: 34.75
    waist: 24.5
    hips: 34.25
    shoulder_across_back: 13.75
    thigh: 18.5
    knee: 13
    calf: 13.5
    ankle: 7.75
    tricep: 8.5
    bicep: 8
    wrist: 6
    arm: 22.5
  2:
    neck: 13
    bust: 35.25
    waist: 25
    hips: 34.75
    shoulder_across_back: 14.25
    thigh: 19
    knee: 14
    calf: 13.5
    ankle: 8.25
    tricep: 9
    bicep: 8.5
    wrist: 6.5
    arm: 23
  4:
    neck: 13.5
    bust: 35.75
    waist: 25.5
    hips: 35.25
    shoulder_across_back: 14.75
    thigh: 19.5
    knee: 14.5
    calf: 14
    ankle: 8.75
    tricep: 9.5
    bicep: 9
    wrist: 7
    arm: 23.5
  6:
    neck: 14
    bust: 36.25
    waist: 26
    hips: 35.75
    shoulder_across_back: 15.25
    thigh: 20
    knee: 15
    calf: 15.5
    ankle: 9.25
    tricep: 10
    bicep: 9.5
    wrist: 7.5
    arm: 24
  8:
    neck: 14.5
    bust: 36.75
    waist: 26.5
    hips: 36.25
    shoulder_across_back: 15.75
    thigh: 20.5
    knee: 15.5
    calf: 16
    ankle: 9.75
    tricep: 10.5
    bicep: 10
    wrist: 8
    arm: 24.5
  10:
    neck: 15
    bust: 37.25
    waist: 27
    hips: 36.75
    shoulder_across_back: 16.25
    thigh: 21
    knee: 16
    calf: 16.5
    ankle: 10.25
    tricep: 11
    bicep: 10.5
    wrist: 8.5
    arm: 25
  12:
    neck: 15.5
    bust: 37.75
    waist: 28
    hips: 37.25
    shoulder_across_back: 16.75
    thigh: 21.5
    knee: 16.5
    calf: 17
    ankle: 10.75
    tricep: 11.5
    bicep: 11
    wrist: 9
    arm: 25.5   