parameters:
#    love_that_fit_admin.example.class: LoveThatFit\AdminBundle\Example

services:
#    love_that_fit_admin.example:
#        class: %love_that_fit_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
constants:
  device_bootstrap:
    resolution_scale:    
      web: 
        pixel_per_inch: 6
        pixel_height : 1152
        inch_height: 72
      iphone4s: 
        pixel_per_inch: 14
        pixel_height : 696
      iphone5:  
        pixel_per_inch: 17
        pixel_height : 870
      ipad:
        pixel_per_inch: 18.125
        pixel_height : 870
      ipad_retina:
        pixel_per_inch: 18.125
        pixel_height : 870
      
  pagination:
    limit: 30
    default_page: first
  
  gender:
    men: m 
    women: f
  
  target: 
     top: top
     bottom: bottom
     dress: dress
     
  body_types:
     ({regular, petite})
 
  body_types_search:
      regular: Regular
      petite: Petite
     
 
  body_shape:
    pear: pear
    hourglass: hourglass
    apple: apple
    
  size_titles:
     ({xxs, xs, s, m, l, xl, xxl})
  
  size_numbers:
     ({0, 1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20})
  
  size_charts:
    xxs: 0
    xs: 1
    xs: 2
    s: 4
    s: 6
    m: 8
    m: 10
    l: 12
    l: 14
    xl: 16
    xl: 18
    xxl: 20
    xxl: 22
    xxl: 24
    xxl: 26
    xxl: 28
 
  bra_size:
    28a: 28a 
    28b: 28b
    28c: 28c
    28d: 28d
    28dd: 28dd
    30a: 30a
    30b: 30b
    30c: 30c
    30d: 30d
    30dd: 30dd
    32a: 32a
    32b: 32b
    32c: 32c
    32d: 32d
    32dd: 32dd
    34a: 34a
    34b: 34b
    34c: 34c
    34d: 34d
    34dd: 34dd
    36a: 36a
    36b: 36b
    36c: 36c
    38a: 38a
    38b: 38b
    38c: 38c
    38d: 38d
    38dd: 38dd
    40a: 40a
    40b: 40b
    40c: 40c
    40d: 40d
    40dd: 40dd


Twitter:  
consumer_key: 9GBx1IchmgsTC404I52w
consumer_secret: HC6fR9dZYl8zqzHNx36eCvlWvJ0HCmPzMJr3Pqj88
oauth_access_token : 1667582922-O5JzsoBc7fmfUR2jYVHrnCWsIiOWDDO38uXwpQk
oauth_access_token_secret: sa0TN4vVjQtU82o09VatP68oLISZjkXd3erZnGk
screen_name: LoveThatFit



    