sku: 
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit' 

waist: 
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit'  
hip:  
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit' 

bust: 
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit' 

arm: 
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit' 

leg: 
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit' 

inseam:  
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit' 

outseam:  
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit' 

hem: 
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit' 

back: 
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit' 

length: 
  lower: 'crossing lower most limit' 
  -2: '2 inch short' 
  -1: '1 inch short' 
  0: 'Exact fit' 
  1: 'One inch bigger' 
  2: '2 inch bigger' 
  adjust: ' adjustment upplied, streched & fit' 
  upper: 'crossing upper most limit' 
