image_category:

  brand:    
    original:
      prefix: 
      dir:  'uploads/ltf/brands'  

    web:
      height: 80
      width: 205
      prefix:  
      dir:  'uploads/ltf/brands/web'  

    iphone:
      width: 100
      height: 106      
      prefix:  
      dir:  'uploads/ltf/brands/iphone'  

  product:
    original:
      prefix: 
      dir:  'uploads/ltf/products/display'
      
    web:
      height: 108
      width: 100
      prefix:   			
      dir:  'uploads/ltf/products/display/web'

    iphone:
      width: 78
      height: 77
      prefix:  
      dir:  'uploads/ltf/products/display/iphone' 
    
    iphone_list:
      width: 145
      height: 117
      prefix:  
      dir:  'uploads/ltf/products/display/iphone_list' 
    
      
  
  product_pattern:      
    original:
      prefix:  
      dir:  'uploads/ltf/products/pattern'  

    web:
      width: 16
      height: 16
      prefix:  
      dir:  'uploads/ltf/products/pattern/web'  
    
    iphone:
      width: 50
      height: 50
      prefix:  
      dir:  'uploads/ltf/products/pattern/iphone' 
      
    ipad:
      width: 80
      height: 80
      prefix:  
      dir:  'uploads/ltf/products/pattern/ipad'  
    
    ipad_retina:
      width: 100
      height: 100
      prefix:  
      dir:  'uploads/ltf/products/pattern/ipad_retina'      

  product_item:
    original:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room'
      pixel_per_inch: 17      
    web:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/web'
      available_height: 1152  
      pixel_per_inch: 6
      
    iphone4s:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/iphone4s'
      available_height: 690  
      pixel_per_inch: 14
       
    iphone5:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/iphone5'
      available_height: 840
      pixel_per_inch: 17 
      
    ipad:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/ipad'
      available_height: 870
      pixel_per_inch: 18.125 
    
    ipad_retina:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/ipad_retina'
      available_height: 870
      pixel_per_inch: 18.125   
      
  user:
    original:
      prefix: 
      dir:  'uploads/ltf/users'
      
    profile:
      prefix: 
      height: 250
      width: 220
      dir:  'uploads/ltf/users'
