image_category:

  retailer:    
    original:
      prefix: 
      dir:  'uploads/ltf/retailers'  

    web:
      height: 126
      width: 126
      prefix:  
      dir:  'uploads/ltf/retailers/web'  
      
    iphone:
      height: 126
      width: 126
      prefix:  
      dir:  'uploads/ltf/retailers/iphone'  
        
  brand:    
    original:
      prefix: 
      dir:  'uploads/ltf/brands'  

    web:
      height: 126
      width: 126
      prefix:  
      dir:  'uploads/ltf/brands/web'  

    iphone:
      height: 126
      width: 126
      prefix:  
      dir:  'uploads/ltf/brands/iphone'  

  product:
    original:
      prefix: 
      dir:  'uploads/ltf/products/display'
      
    web:
      height: 108
      width: 100
      prefix:   			
      dir:  'uploads/ltf/products/display/web'

    iphone:
      width: 78
      height: 77
      prefix:  
      dir:  'uploads/ltf/products/display/iphone' 
        
    iphone_list:
      width: 145
      height: 117
      prefix:  
      dir:  'uploads/ltf/products/display/iphone_list' 
    
    iphone5_product_list:
       width: 320
       height: 240
       prefix:  
       dir:  'uploads/ltf/products/display/iphone5_product_list' 
       
    iphone5_list:
       width: 295
       height: 403
       prefix:  
       dir:  'uploads/ltf/products/display/iphone5_list' 
      
    iphone5_fitting_alert:
       width: 251
       height: 294
       prefix:  
       dir:  'uploads/ltf/products/display/iphone5_fitting_alert' 
      
    iphone5_fitting_room_list:
       width: 110
       height: 152
       prefix:  
       dir:  'uploads/ltf/products/display/iphone5_fitting_room_list' 

    iphone6_list:
       width: 345
       height: 472
       prefix:  
       dir:  'uploads/ltf/products/display/iphone6_list' 

    iphone6_fitting_alert:
       width: 251
       height: 343
       prefix:  
       dir:  'uploads/ltf/products/display/iphone6_fitting_alert' 

    iphone6_fitting_room_list:
       width: 129
       height: 177
       prefix:  
       dir:  'uploads/ltf/products/display/iphone6_fitting_room_list' 
      
      
  product_pattern:      
    original:
      prefix:  
      dir:  'uploads/ltf/products/pattern'  

    web:
      width: 16
      height: 16
      prefix:  
      dir:  'uploads/ltf/products/pattern/web'  
    
    iphone:
      width: 50
      height: 50
      prefix:  
      dir:  'uploads/ltf/products/pattern/iphone' 
      
    ipad_retina:
      width: 100
      height: 100
      prefix:  
      dir:  'uploads/ltf/products/pattern/ipad_retina'      

  product_item:
    original:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room'
      pixel_per_inch: 60      
      
    web:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/web'
      available_height: 1152  
      pixel_per_inch: 6
       
    iphone5:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/iphone5'
      available_height: 840
      pixel_per_inch: 17 
      
    ipad:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/ipad'
      available_height: 870
      pixel_per_inch: 18.125 
    
  user:
    original:
      prefix: 
      dir:  'uploads/ltf/users'
      
    profile:
      prefix: 
      height: 250
      width: 220
      dir:  'uploads/ltf/users'


image_map:
  brand:
    web:
      height: 80
      width: 205
    phone:
      width: 120
      height: 120      
    tab:
      width: 120
      height: 120
  retailer:
    web:
      height: 80
      width: 205
    phone:
      width: 120
      height: 120      
    tab:
      width: 120
      height: 120
  products:
    web:
      height: 108
      width: 100
    phone:
      width: 120
      height: 120      
    tab:
      width: 120
      height: 120
  products_pattern:
    web:
      height: 16
      width: 16
    phone:
      width: 50
      height: 50      
    tab:
      width: 100
      height: 100
  products_item: