image_category:

  brand:
    original:
      prefix: 
      dir:  'uploads/ltf/brands'

    icon:
      height: 40
      width: 35
      prefix:  
      dir:  'uploads/ltf/brands/icon'
    
    logo:
      height: 80
      width: 205
      prefix:  
      dir:  'uploads/ltf/brands/logo'  

  product:
    original:
      prefix: 
      dir:  'uploads/ltf/products'

    icon:
      height: 40
      width: 35
      prefix:  
      dir:  'uploads/ltf/products/list'

    small:
      height: 110
      width: 85
      prefix:  
      dir:  'uploads/ltf/products/small'

    large:
      height: 240
      width: 200
      prefix:   			
      dir:  'uploads/ltf/products/large'
  
  product_item:
    original:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room'
      available_height: 1152
      pixel_per_inch: 25  
    34px:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/34'
      pixel_per_inch: 34
    30px:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/30'
      pixel_per_inch: 30      
    25px:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/25'
      pixel_per_inch: 25    
    17px:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/17'
      pixel_per_inch: 17      
    14px:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/14'
      pixel_per_inch: 14            
    11px:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/11'
      pixel_per_inch: 11      
    8px:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/8'
      pixel_per_inch: 8            
    6px:
      prefix: 
      dir:  'uploads/ltf/products/fitting_room/6'
      pixel_per_inch: 6            
#    iphone4s:
#      prefix: 
#      dir:  'uploads/ltf/products/fitting_room/iphone4s'
#      available_height: 690  
    
#    iphone5:
#      prefix: 
#      dir:  'uploads/ltf/products/fitting_room/iphone5'
#      available_height: 840
    
 #   ipad:
 #     prefix: 
 #     dir:  'uploads/ltf/products/fitting_room/ipad'
 #     available_height: 1024    
    
 #   ipad_retuna:
 #     prefix: 
 #     dir:  'uploads/ltf/products/fitting_room/ipad_retuna'
 #     available_height: 2048   
  
  user:
    original:
      prefix: 
      dir:  'uploads/ltf/users'
      
    profile:
      prefix: 
      height: 250
      width: 220
      dir:  'uploads/ltf/users'
