parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: dc4c6bee1d9e9fed81c4f06885e38498e7ef76be
    database_path: null
