support_fit_evaluation_sheet_print:
    pattern:  /support/evaluation_sheet/print
    defaults: { _controller: LoveThatFitSupportBundle:EvaluationSheet:print}

support_fit_evaluation_sheet_csv:
    pattern:  /support/evaluation_sheet/csv
    defaults: { _controller: LoveThatFitSupportBundle:EvaluationSheet:csv}

support_evaluation_sheet_index:
    pattern:  /support/evaluation_sheet
    defaults: { _controller: LoveThatFitSupportBundle:EvaluationSheet:index}

support_evaluation_sheet_sample_products:
    pattern:  /support/evaluation_sheet/sample
    defaults: { _controller: LoveThatFitSupportBundle:EvaluationSheet:sample}

support_evaluation_sheet_cart:
    pattern:  /support/evaluation_sheet/cart
    defaults: { _controller: LoveThatFitSupportBundle:EvaluationSheet:cart}

support_evaluation_sheet_favourite:
    pattern:  /support/evaluation_sheet/favourite
    defaults: { _controller: LoveThatFitSupportBundle:EvaluationSheet:favourite}