support_pending_users:
    pattern:  /support/pendingUsers
    defaults: { _controller: LoveThatFitSupportBundle:User:pendingUsers}

support_pending_users_paginate:
    pattern:  /support/pendingUsers/paginate
    defaults: { _controller: LoveThatFitSupportBundle:User:pendingUsersPaginate}

support_pending_users_assign:
    pattern:  /support/pendingUsers/assign
    defaults: { _controller: LoveThatFitSupportBundle:User:assignPendingUsers}

support_pending_users_task_logs_add:
    pattern:  /support/pendingUsers/support_users/add
    defaults: { _controller: LoveThatFitSupportBundle:User:addPendingUsersTaskLog}

support_pending_users_task_logs_remove:
    pattern:  /support/pendingUsers/support_users/remove
    defaults: { _controller: LoveThatFitSupportBundle:User:removePendingUsersTaskLog}