selfieshare_feedback_edit:
    pattern:   /selfieshare/feedback_edit/{ref}
    defaults: { _controller: LoveThatFitUserBundle:SelfieShare:feedbackEdit, ref: null }

selfieshare_feedback_update:
    pattern:   /selfieshare/feedback_update
    defaults: { _controller: LoveThatFitUserBundle:SelfieShare:feedbackUpdate }
        
selfieshare_feedback_show:
    pattern:   /selfieshare/feedback_show/{ref}
    defaults: { _controller: LoveThatFitUserBundle:SelfieShare:feedbackShow, ref: null }    
