love_that_fit_cart:
   environment: sandbox
   merchant_id: 999xtbqc2s55bx9c
   public_key:  jg2z77t3jkp43j8g
   private_key: 18fee97bc8564dfec7d0c1670f592386

braintree_live:
   environment: production
   merchant_id: dtjkgnd4hzfnwpk7
   public_key:  f8p6mc39tm5m7nv2
   private_key: 292fcf8da61e8a9e8db5e0eff990002a

stamps_com_dev:
  environment: developement
  integrarionId: b8b61439-52e6-4d19-a51f-a3422c8a79e9
  userName: SelfieStyl-001
  password: postage1
  fromzipcode: 90405
  serviceType: US-XM
  weightOz: 500
  packagetype: Package
  deliverydays: 1-3
