
admin_algorithm_avg:
    pattern:  /admin/algorithm/avg
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:avg}

admin_algorithm_avg_comparison:
    pattern:  /admin/algorithm/avg_comparison/{user_id}/{product_id}/{json}
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:avgComparison, user_id: 0, product_id: 0, json:false}
#-------------------------------------------------------
admin_algorithm_comparison:
    pattern:  /admin/algorithm/comparison
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:comparison}

admin_algorithm_compare:
    pattern:  /admin/algorithm/compare/{user_id}/{product_id}/{json}
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:compare, user_id: 0, product_id: 0, json:false}
#-------------------------------------------------------
admin_algorithm_foo:
    pattern:  /admin/algorithm/foo/{user_id}/{product_id}/{size_id}
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:foo, user_id: 0, product_id: 0, size_id: 0}
    