admin_fit_algorithm2_index:
    pattern:  /admin/fit_algorithm2/index
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:FitAlgorithmIndex}

admin_fit_algorithm2_comparision:
    pattern:  /admin/fit_algorithm2/compare/{user_id}/{product_id}/{json}
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:FitAlgorithmCompare, user_id: 0, product_id: 0, json: 0}

admin_fit_algorithm2_product_list_index:
    pattern:  /admin/fit_algorithm2/product_list_index
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:productList}

admin_fit_algorithm2_user_product_marathon:
    pattern:  /admin/fit_algorithm2/user_product_marathon
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:userProductMarathon}

admin_fit_algorithm2_print_user_product_marathon:
    pattern:  /admin/fit_algorithm2/print_user_product_marathon
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:printUserProductMarathon}

admin_fit_algorithm2_download_csv_result:
    pattern:  /admin/fit_algorithm2/download_csv_results
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:downloadCsvResults}

admin_test_demo:
    pattern:  /admin/fit_algorithm2/user_test_demo
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:userTestDemo}

admin_test_demo_products:
    pattern:  /admin/fit_algorithm2/user_test_demo_products
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:userTestDemoProducts}
    
admin_test_demo_product_list:
    pattern:  /admin/fit_algorithm2/user_test_demo_product_list/{user_id}
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:userTestDemoProductList}    
    
admin_evaluation_sheet_foo:
    pattern:  /admin/fit_algorithm2/foo/{user_id}
    defaults: { _controller: LoveThatFitAdminBundle:Algorithm:foo}        