admin_clothing_types:
    pattern:  /admin/clothing_types/{page_number}/{sort}
    defaults: { _controller: LoveThatFitAdminBundle:ClothingType:index ,page_number: 1, sort:id }

admin_clothing_type_show:
    pattern:  /admin/clothing_type/{id}/show
    defaults: { _controller: LoveThatFitAdminBundle:ClothingType:show }
    
admin_clothing_type_new:
    pattern:  /admin/clothing_type/new
    defaults: { _controller: LoveThatFitAdminBundle:ClothingType:new }

admin_clothing_type_create:
    pattern:  /admin/clothing_type/create
    defaults: { _controller: LoveThatFitAdminBundle:ClothingType:create }
    requirements: 
      _method: post 
    
admin_clothing_type_edit:
    pattern:  /admin/clothing_type/{id}/edit
    defaults: { _controller: LoveThatFitAdminBundle:ClothingType:edit }
    requirements:
        _method:  GET
        
admin_clothing_type_update:
    pattern:  /admin/clothing_type/{id}/update
    defaults: { _controller: LoveThatFitAdminBundle:ClothingType:update }
    requirements:
        _method:  POST
        
admin_clothing_type_delete:
    pattern:  /admin/clothing_type/{id}/delete
    defaults: { _controller: LoveThatFitAdminBundle:ClothingType:delete }
    
        