
admin_product_show:
    pattern:  /admin/product/{id}/show
    defaults: { _controller: LoveThatFitAdminBundle:Product:show }
    
admin_products:
    pattern:  /admin/products/{page_number}/{sort}
    defaults: { _controller: LoveThatFitAdminBundle:Product:index , page_number: 1, sort:id}

admin_product_new:
    pattern:  /product/new
    defaults: { _controller: LoveThatFitAdminBundle:Product:new }

admin_product_create:
    pattern:  /product/create
    defaults: { _controller: LoveThatFitAdminBundle:Product:create }
    requirements: { _method: post }


admin_product_edit:
    pattern:  /product/{id}/edit
    defaults: { _controller: LoveThatFitAdminBundle:Product:edit }

admin_product_update:
    pattern:  /admin/product/{id}/update
    defaults: { _controller: LoveThatFitAdminBundle:Product:update }
    requirements: { _method: post } 
    
admin_product_delete:
    pattern:  /product/{id}/delete
    defaults: { _controller: LoveThatFitAdminBundle:Product:delete }

#--------------------------- Product Details --------------    
    
admin_product_detail_new:
     pattern:  /admin/product/product_detail/new
     defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailNew }

admin_product_detail_create:
     pattern:  /admin/product/product_detail/create
     defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailCreate}

admin_product_detail_show:
    pattern:  /admin/productdetail/{id}
    defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailShow }     
admin_product_detail_edit:
    pattern:  /admin/productdetail/{id}/edit
    defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailEdit }
admin_product_detail_update:
   pattern:  /admin/productdetail/{id}/update
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailUpdate }

admin_product_detail_delete:
   pattern:  /admin/productdetail/{id}/delete
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailDelete }
   
#--------------------------- Product Color --------------       
   
admin_product_detail_color_create:
   pattern:  /admin/productdetail/{id}/color/create
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailColorCreate }   
  
     
#--------------------------- Product Sizes --------------       
   
admin_product_detail_size_edit:
   pattern:  /admin/productdetail/{id}/size/{size_id}/edit
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailSizeEdit }   
  
admin_product_detail_size_update:
   pattern:  /admin/productdetail/{id}/size/{size_id}/update
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailSizeUpdate }   
admin_product_detail_size_delete:
   pattern:  /admin/productdetail/{id}/size/{size_id}/delete
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailSizeDelete }   
    
#--------------------------- Product Items --------------       
   
admin_product_detail_item_edit:
   pattern:  /admin/productdetail/{id}/item/{item_id}/edit
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailItemEdit }   
  
admin_product_detail_item_update:
   pattern:  /admin/productdetail/{id}/item/{item_id}/update
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailItemUpdate } 
admin_product_detail_item_delete:
   pattern:  /admin/productdetail/{id}/delete/{item_id}/edit
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailItemDelete }   
   