
admin_product_show:
    pattern:  /admin/product/{id}/show
    defaults: { _controller: LoveThatFitAdminBundle:Product:show }
    
admin_products:
    pattern:  /admin/products/{page_number}/{sort}
    defaults: { _controller: LoveThatFitAdminBundle:Product:index , page_number: 1, sort:id}

admin_product_new:
    pattern:  /product/new
    defaults: { _controller: LoveThatFitAdminBundle:Product:new }

admin_product_create:
    pattern:  /product/create
    defaults: { _controller: LoveThatFitAdminBundle:Product:create }
    requirements: { _method: post }


admin_product_edit:
    pattern:  /product/{id}/edit
    defaults: { _controller: LoveThatFitAdminBundle:Product:edit }

admin_product_update:
    pattern:  /admin/product/{id}/update
    defaults: { _controller: LoveThatFitAdminBundle:Product:update }
    requirements: { _method: post } 
    
admin_product_delete:
    pattern:  /product/{id}/delete
    defaults: { _controller: LoveThatFitAdminBundle:Product:delete }
    
admin_product_detail_new:
     pattern:  /admin/product/product_detail/new
     defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailNew }

admin_product_detail_create:
     pattern:  /admin/product/product_detail/create
     defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailCreate}

admin_product_detail_show:
    pattern:  /admin/productdetail/{id}/show
    defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailShow }     
admin_product_detail_edit:
    pattern:  /admin/productdetail/{id}/edit
    defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailEdit }
admin_product_detail_update:
   pattern:  /admin/productdetail/{id}/update
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailUpdate }
admin_product_detail_delete:
   pattern:  /admin/productdetail/{id}/delete
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailDelete }
   
admin_product_detail_color_create:
   pattern:  /admin/productdetail/color/{id}/create
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailColorCreate }   
  
     
    
    