admin_product_specs_list:
    pattern:  /admin/product_specs/list
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:list }
    
admin_product_specs_edit:
    pattern:  /admin/product_specs/{id}/edit
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:edit }
    

admin_product_specs_mapping_save:
    pattern:  /admin/product_specs/mapping_save
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:mappingSave }
    
admin_product_specs_csv_upload:
    pattern:  /admin/product_specs/csv_upload
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:csvUpload }

admin_product_specs_csv_data_input:
    pattern:  /admin/product_specs/csv_data_input
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:csvDataInput }

admin_product_specs_csv_data_upload:
    pattern:  /admin/product_specs/csv_data_upload
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:csvDataUpload }

admin_product_specs_foo:
    pattern:  /admin/product_specs/foo
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:foo }

admin_product_specs_bar:
    pattern:  /admin/product_specs/bar  
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:bar }

admin_product_specs_map:
    pattern:  /admin/product_specs/mapping_input
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:mappingInput }    

