
#--------------------------- Product Wizard Steps --------------       

admin_product_entry_wizard_detail_new:
     pattern:  /admin/products/entry_wizard/new
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardNew }
admin_product_entry_wizard_detail_create:
     pattern:  /admin/products/entry_wizard/create
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardCreate }
admin_product_entry_wizard_detail_edit:
     pattern:  /admin/products/{id}/entry_wizard/edit
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardEdit }
admin_product_entry_wizard_detail_update:
     pattern:  /admin/products/{id}/entry_wizard/update
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardUpdate }

admin_product_entry_wizard_colors:
     pattern:  /admin/products/{id}/entry_wizard/colors
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardColors }
admin_product_entry_wizard_color_new:
     pattern:  /admin/products/{id}/entry_wizard/color/new
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardColorNew }
admin_product_entry_wizard_color_create:
     pattern:  /admin/products/{id}/entry_wizard/color/create
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardColorCreate }
admin_product_entry_wizard_color_edit:
     pattern:  /admin/products/{id}/entry_wizard/color/{color_id}/edit
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardColorEdit }
admin_product_entry_wizard_color_update:
     pattern:  /admin/products/{id}/entry_wizard/color/{color_id}/update
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardColorUpdate }


admin_product_entry_wizard_sizes:
     pattern:  /admin/products/{id}/entry_wizard/sizes
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardSizes }
admin_product_entry_wizard_size_new:
     pattern:  /admin/products/{id}/entry_wizard/size/new
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardSizeNew }
admin_product_entry_wizard_size_create:
     pattern:  /admin/products/{id}/entry_wizard/size/create
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardSizeCreate }
admin_product_entry_wizard_size_edit:
     pattern:  /admin/products/{id}/entry_wizard/size/{size_id}/edit
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardSizeEdit }
admin_product_entry_wizard_size_update:
     pattern:  /admin/products/{id}/entry_wizard/size/{size_id}/update
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardSizeUpdate }

admin_product_entry_wizard_items:
     pattern:  /admin/products/{id}/entry_wizard/items
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardItems }
admin_product_entry_wizard_item_new:
     pattern:  /admin/products/{id}/entry_wizard/item/{color_id}/{size_id}/new
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardItemNew }
admin_product_entry_wizard_item_create:
     pattern:  /admin/products/{id}/entry_wizard/item/{color_id}/{size_id}/create
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardItemCreate }
admin_product_entry_wizard_item_edit:
     pattern:  /admin/products/{id}/entry_wizard/item/{item_id}/edit
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardItemEdit }
admin_product_entry_wizard_item_update:
     pattern:  /admin/products/{id}/entry_wizard/item/{item_id}/update
     defaults: { _controller: LoveThatFitAdminBundle:Product:productEntryWizardItemUpdate }


  
#-------------------------------------------------------------
admin_products:
    pattern:  /admin/products/{page_number}/{sort}
    defaults: { _controller: LoveThatFitAdminBundle:Product:index , page_number: 1, sort:id}


#--------------------------- Product Details --------------    
    
admin_product_detail_new:
     pattern:  /admin/product/product_detail/new
     defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailNew }

admin_product_detail_create:
     pattern:  /admin/product/product_detail/create
     defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailCreate}

admin_product_detail_show:
    pattern:  /admin/productdetail/{id}
    defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailShow }     
admin_product_detail_edit:
    pattern:  /admin/productdetail/{id}/edit
    defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailEdit }
admin_product_detail_update:
   pattern:  /admin/productdetail/{id}/update
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailUpdate }

admin_product_detail_delete:
   pattern:  /admin/productdetail/{id}/delete
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailDelete }
   
admin_product_stats:
   pattern:  /admin/product/stats
   defaults: { _controller: LoveThatFitAdminBundle:Product:productStats }
admin_product_detail_download:
   pattern:  /admin/productdetail/{id}/download
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDownloads }

   

     
     
   
#--------------------------- Product Color --------------       

admin_product_detail_color_image_upload:
   pattern:  /admin/productdetail/{id}/color/image_upload
   defaults: { _controller: LoveThatFitAdminBundle:Product:productColorTemporaryImageUpload,_format: json} 

admin_product_detail_color_create:
   pattern:  /admin/productdetail/{id}/color/create
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailColorCreate }   

admin_product_detail_color_add:
   pattern:  /admin/productdetail/{id}/color/add
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailColorAddNew }
   
admin_product_detail_color_edit:
   pattern:  /admin/productdetail/{id}/color/{color_id}/edit
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailColorEdit }
admin_product_detail_color_update:
   pattern:  /admin/productdetail/{id}/color/{color_id}/update
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailColorUpdate }   
admin_product_detail_color_delete:
   pattern:  /admin/productdetail/{id}/color/{color_id}/delete
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailColorDelete }  
  
#--------------------------- Product Sizes --------------       
   
admin_product_detail_size_edit:
   pattern:  /admin/productdetail/{id}/size/{size_id}/edit
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailSizeEdit }   
  
admin_product_detail_size_update:
   pattern:  /admin/productdetail/{id}/size/{size_id}/update
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailSizeUpdate }   
admin_product_detail_size_delete:
   pattern:  /admin/productdetail/{id}/size/{size_id}/delete
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailSizeDelete }   
    
#--------------------------- Product Items --------------       
   
admin_product_detail_item_edit:
   pattern:  /admin/productdetail/{id}/item/{item_id}/edit
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailItemEdit }   
  
admin_product_detail_item_update:
   pattern:  /admin/productdetail/{id}/item/{item_id}/update
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailItemUpdate } 
admin_product_detail_item_delete:
   pattern:  /admin/productdetail/{id}/delete/{item_id}/edit
   defaults: { _controller: LoveThatFitAdminBundle:Product:productDetailItemDelete }   
   