
admin_product_specs_csv_upload:
    pattern:  /admin/product_specs/csv_upload
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:csvUpload }

admin_product_specs_foo:
    pattern:  /admin/product_specs/foo
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:foo }

admin_product_specs_bar:
    pattern:  /admin/product_specs/bar  
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:bar }

admin_product_specs_map:
    pattern:  /admin/product_specs/mapping_input
    defaults: { _controller: LoveThatFitAdminBundle:ProductSpecs:mappingInput }    

