sent_email:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/sent_email.yml"
    prefix:   /

#-------------------------------------------------------------
#-------------- ADMIN ------------------------
#-------------------------------------------------------------

admin_dashboard:
    pattern:  /admin/dashboard
    defaults: { _controller: LoveThatFitAdminBundle:Default:index}

#-------------- User Mask adjustment ------------------------
    
admin_user_mask_adjustment_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/user_mask_adjustment.yml"
    prefix:   /
#-------------- PRODUCT ------------------------
    
admin_product_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/product.yml"
    prefix:   /

#-------------- PRODUCT COLOR VIEW------------------------
    
admin_product_color_view_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/product_color_view.yml"
    prefix:   /
#-------------- BRAND ------------------------

admin_brand_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/brand.yml"
    prefix:   /

#-------------- ORDER ------------------------

admin_order_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/order.yml"
    prefix:   /



    #-------------- CLOTHING TYPE ------------------------
    
admin_clothing_type_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/clothing_type.yml"
    prefix:   /
    
admin_survey_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/survey.yml"
    prefix:   /

admin_sizechart_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/sizechart.yml"
    prefix:   /

admin_user_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/user.yml"
    prefix:   /

    #-------------- Product Wizard Route ------------------------
admin_product_wizard_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/productwizard.yml"
    prefix:   /
    
    #-------------- Retailer User Route ------------------------
admin_retailer_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/retailer.yml"
    prefix:   /
    
     #-------------- Algorithm Route ------------------------
admin_algoritm_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/algorithm.yml"
    prefix:   /
    
admin_product_data_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/product_data.yml"
    prefix:   /   
    #---------------------------Push Notification Interface ------------------#
admin_push_notification:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/push_notification.yml"
    prefix:   /       
    
#-------------- Masked Marker ------------------------
    
admin_mask_marker_inspect_routes:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/mask_marker_inspect.yml"
    prefix:   /

#-------------- Auto Complete  ------------------------

admin_auto_complete:
    resource: "@LoveThatFitAdminBundle/Resources/config/routing/auto_complete.yml"
    prefix:   /