#~~~~~~~~~~~~~~~~> Default
shopify_install:
    pattern:  /shopify/install
    defaults: { _controller: LoveThatFitShopifyBundle:Default:install }

shopify_granted:
    pattern:  /shopify/granted
    defaults: { _controller: LoveThatFitShopifyBundle:Default:granted }

shopify_foo:
    pattern:  /shopify/foo
    defaults: { _controller: LoveThatFitShopifyBundle:Default:foo }

shopify_simulator:
    pattern:  /shopify/simulator
    defaults: { _controller: LoveThatFitShopifyBundle:Default:shopifySimulator }
 
shopify_user_check:
    pattern:  /shopify/user_check/{user_id}/{sku}
    defaults: { _controller: LoveThatFitShopifyBundle:Default:userCheck ,user_id:0,sku:0}    
 

#~~~~~~~~~~~~~~~~> Data 
shopify_data_index:
    pattern:  /shopify/data/index
    defaults: { _controller: LoveThatFitShopifyBundle:Data:index }    

shopify_data_sku_upload:
    pattern:  /shopify/data/sku_upload
    defaults: { _controller: LoveThatFitShopifyBundle:Data:skuUpload }    