shopify_index:
    pattern:  /shopify/index
    defaults: { _controller: LoveThatFitShopifyBundle:Default:index }

shopify_granted:
    pattern:  /shopify/granted
    defaults: { _controller: LoveThatFitShopifyBundle:Default:granted }

shopify_products:
    pattern:  /shopify/products
    defaults: { _controller: LoveThatFitShopifyBundle:Default:products }

shopify_fitting_room:
    pattern:  /shopify/fitting_room
    defaults: { _controller: LoveThatFitShopifyBundle:Default:fittingRoom }
