#~~~~~~~~~~~~~~~~> Default
shopify_install:
    pattern:  /shopify/install
    defaults: { _controller: LoveThatFitShopifyBundle:Default:install }

shopify_granted:
    pattern:  /shopify/granted
    defaults: { _controller: LoveThatFitShopifyBundle:Default:granted }

shopify_foo:
    pattern:  /shopify/foo
    defaults: { _controller: LoveThatFitShopifyBundle:Default:foo }

shopify_simulator:
    pattern:  /shopify/simulator
    defaults: { _controller: LoveThatFitShopifyBundle:Default:shopifySimulator }
 
shopify_user_check:
    pattern:  /shopify/user_check/{access_token}/{user_id}/{sku}
    defaults: { _controller: LoveThatFitExternalSiteBundle:Default:proxyFittingRoom ,access_token:0,user_id:0,sku:0}    
 
shopify_app_proxy:
    pattern:  /shopify/app_proxy/{sku}
    defaults: { _controller: LoveThatFitShopifyBundle:Default:checkSku,sku:0}    
    
shopify_customer_list:
    pattern:  /shopify/customer_list
    defaults: { _controller: LoveThatFitShopifyBundle:Default:getCustomerList}    

#~~~~~~~~~~~~~~~~> Data 
shopify_data_index:
    pattern:  /shopify/data/index
    defaults: { _controller: LoveThatFitShopifyBundle:Data:index }    

shopify_data_sku_upload:
    pattern:  /shopify/data/sku_upload
    defaults: { _controller: LoveThatFitShopifyBundle:Data:skuUpload }    
    
 #------------------Test Controller ----------
shopify_test_start:
    pattern:  /shopify/test/install
    defaults: { _controller: LoveThatFitShopifyBundle:Test:install }    

shopify_test_granted:
    pattern:  /shopify/test/granted
    defaults: { _controller: LoveThatFitShopifyBundle:Test:granted }
    

 