'api_key' : '584e96437b334b01028908e63a602204'
'shared_secret': '0d694e4a176838a97fa10d3dd81491dd'

app_scopes:
  [read_products, write_themes, write_content, read_customers, read_orders]
  
webhooks:
  orders_create:
    topic: "orders/create"
    address: "/shopify/webhook/order_create"
  cart_create:
    topic: "cart/create"
    address:  "/shopify/webhook/cart_create"


    #    $api_key = '584e96437b334b01028908e63a602204';
    #    $shared_secret = '0d694e4a176838a97fa10d3dd81491dd';
    #    $shop_domain = 'lovethatfit-2.myshopify.com';    
    #    $access_token = '8b14eb6efcf7c5fa7b0c76e9b329d06e';
         