'api_key' : '584e96437b334b01028908e63a602204'
'shared_secret': '0d694e4a176838a97fa10d3dd81491dd'

app_scopes:
  [read_products, write_themes, write_content, read_customers, read_orders]
  
webhooks:
  orders_create:
    topic: "orders/create"
    address: "/shopify/webhook/order_create_callback"
  orders_updated:
    topic: "orders/updated"
    address: "/shopify/webhook/order_updated_callback"
  orders_paid:
    topic: "orders/paid"
    address: "/shopify/webhook/order_paid_callback"
  orders_fulfilled:
    topic: "orders/fulfilled"
    address: "/shopify/webhook/order_fullfilled_callback"
  orders_cancelled:
    topic: "orders/cancelled"
    address: "/shopify/webhook/order_fullfilled_callback"
  cart_create:
    topic: "carts/create"
    address:  "/shopify/webhook/cart_create_callback"
    


    #    $api_key = '584e96437b334b01028908e63a602204';
    #    $shared_secret = '0d694e4a176838a97fa10d3dd81491dd';
    #    $shop_domain = 'lovethatfit-2.myshopify.com';    
    #    $access_token = '8b14eb6efcf7c5fa7b0c76e9b329d06e';
         